from database import SessionLocal, engine, Base
from models import Mot

Base.metadata.create_all(bind=engine)

VOCABULAIRE = [
    # ── Emploi / RH ──────────────────────────────────────────
    ("a company", "une entreprise", "emploi"),
    ("a job", "un travail", "emploi"),
    ("a job interview", "un entretien d'embauche", "emploi"),
    ("to fire someone", "licencier quelqu'un", "emploi"),
    ("to hire someone", "embaucher quelqu'un", "emploi"),
    ("to get a job", "obtenir un poste", "emploi"),
    ("salary", "salaire", "emploi"),
    ("a raise", "une augmentation", "emploi"),
    ("a course / a training", "une formation", "emploi"),
    ("a promotion", "une promotion", "emploi"),
    ("employment", "l'emploi", "emploi"),
    ("a CV / a résumé", "un CV", "emploi"),
    ("a job application", "une candidature", "emploi"),
    ("the skills", "les compétences", "emploi"),
    ("a colleague / a coworker", "le collègue", "emploi"),
    ("a deadline", "la date limite", "emploi"),
    ("a position", "le poste", "emploi"),
    ("to terminate", "licencier", "emploi"),
    ("a corporation", "une société", "emploi"),
    ("the corporate world", "le monde du travail", "emploi"),
    ("the workplace", "le lieu de travail", "emploi"),
    ("workload", "la charge de travail", "emploi"),
    ("to work overtime", "faire des heures supplémentaires", "emploi"),
    ("layoff", "le licenciement", "emploi"),
    ("shift", "la période de travail", "emploi"),
    ("to work part-time", "travailler à temps partiel", "emploi"),
    ("to work full-time", "travailler à temps plein", "emploi"),
    ("perks", "avantages en nature", "emploi"),
    ("payroll", "la paie", "emploi"),
    ("the job market", "le marché de l'emploi", "emploi"),
    ("termination notice", "l'avis de licenciement", "emploi"),
    ("human resources", "les ressources humaines", "emploi"),
    ("career path", "la trajectoire de carrière", "emploi"),
    ("retirement", "la retraite", "emploi"),
    ("teamwork", "le travail d'équipe", "emploi"),
    ("job satisfaction", "la satisfaction au travail", "emploi"),
    ("skillset", "l'ensemble de compétences", "emploi"),
    ("performance review", "l'évaluation de performance", "emploi"),
    ("temporary work", "le travail temporaire", "emploi"),
    ("work-life balance", "l'équilibre travail-vie", "emploi"),
    ("amenities", "équipements", "emploi"),
    ("memo", "une note de service", "emploi"),
    ("meeting", "réunion", "emploi"),
    ("to gather / to meet", "se réunir", "emploi"),
    ("a schedule", "un emploi du temps", "emploi"),
    ("a manager", "un responsable", "emploi"),
    ("to apply for a job", "postuler pour un poste", "emploi"),
    ("a workshop", "un atelier", "emploi"),
    ("an invoice", "une facture", "emploi"),
    ("an applicant", "un candidat", "emploi"),
    ("catering", "restauration", "emploi"),
    ("to attend a conference", "participer à une conférence", "emploi"),
    ("a desk / an office", "un bureau", "emploi"),
    ("overtime", "heures supplémentaires", "emploi"),
    ("education", "les études", "emploi"),
    ("diploma", "diplôme", "emploi"),
    ("certificate", "certification", "emploi"),
    ("award", "récompense", "emploi"),
    ("contractor", "un sous-traitant", "emploi"),
    ("a freelancer", "un freelance", "emploi"),
    ("to commute", "faire le trajet domicile-travail", "emploi"),
    ("trainee / an intern", "stagiaire", "emploi"),
    ("internship", "stage", "emploi"),
    ("an executive", "un cadre", "emploi"),
    ("team", "équipe", "emploi"),
    ("the boss", "le patron / la patronne", "emploi"),
    ("to clock in", "pointer", "emploi"),
    ("benefits", "avantages", "emploi"),
    ("a company car", "une voiture de société", "emploi"),
    ("to retire", "prendre sa retraite", "emploi"),
    ("a sick leave", "congé maladie", "emploi"),
    ("headquarters", "quartier général / siège social", "emploi"),
    ("leisure", "loisirs", "emploi"),
    ("an income", "revenu", "emploi"),
    ("jobless", "sans emploi", "emploi"),
    ("a complaint", "une plainte", "emploi"),
    ("an employee", "un employé", "emploi"),
    ("an employer", "un employeur", "emploi"),
    ("to be self-employed", "travailler à son compte", "emploi"),
    ("a vacancy", "un poste vacant", "emploi"),

    # ── Divertissement / Vie sociale ─────────────────────────
    ("to eat out", "manger au restaurant", "divertissement"),
    ("take-away", "à emporter", "divertissement"),
    ("appetizers", "apéritif", "divertissement"),
    ("starters", "l'entrée", "divertissement"),
    ("a dish", "un plat", "divertissement"),
    ("enjoy your meal", "bon appétit", "divertissement"),
    ("the main course", "le plat principal", "divertissement"),
    ("leftovers", "des restes", "divertissement"),
    ("to order", "commander", "divertissement"),
    ("the bill", "l'addition", "divertissement"),
    ("a tip", "un pourboire", "divertissement"),
    ("a waiter / a waitress", "un serveur", "divertissement"),
    ("napkin", "serviette", "divertissement"),
    ("to binge watch", "regarder pleins de séries de suite", "divertissement"),
    ("TV series", "une série", "divertissement"),
    ("the movie theatre / the cinema", "cinéma", "divertissement"),
    ("a movie", "un film", "divertissement"),
    ("a documentary", "un documentaire", "divertissement"),
    ("to shoot", "filmer / tourner", "divertissement"),
    ("a biopic", "une biographie filmée", "divertissement"),
    ("sci-fi", "film de science-fiction", "divertissement"),
    ("entertaining", "divertissant", "divertissement"),
    ("to play an instrument", "jouer un instrument", "divertissement"),
    ("to hang out with", "traîner avec", "divertissement"),
    ("customer", "client", "divertissement"),
    ("reservation / booking", "réservation", "divertissement"),
    ("clerk", "vendeur", "divertissement"),
    ("a beverage", "une boisson", "divertissement"),
    ("groceries", "courses / provisions", "divertissement"),
    ("cart", "chariot", "divertissement"),
    ("a discount", "une promotion / remise", "divertissement"),
    ("abroad", "à l'étranger", "divertissement"),
    ("price tag", "étiquette de prix", "divertissement"),
    ("junk food", "malbouffe", "divertissement"),
    ("affordable", "abordable", "divertissement"),
    ("shelf", "étagère", "divertissement"),
    ("cheap", "bon marché", "divertissement"),
    ("expensive", "cher", "divertissement"),
    ("range", "gamme", "divertissement"),
    ("organic", "bio", "divertissement"),
    ("the checkout", "la caisse", "divertissement"),
    ("cartoon", "dessin animé", "divertissement"),
    ("to be released", "sortir (au cinéma)", "divertissement"),
    ("to edit", "monter (un film)", "divertissement"),
    ("soap opera", "une comédie à l'eau de rose", "divertissement"),
    ("romcom", "comédie romantique", "divertissement"),
    ("a scriptwriter", "un scénariste", "divertissement"),
    ("the plot", "l'intrigue", "divertissement"),
    ("a trailer", "la bande annonce", "divertissement"),
    ("to go to the cinema", "aller au cinéma", "divertissement"),
    ("to dub", "doubler", "divertissement"),
    ("subtitles", "sous-titres", "divertissement"),
    ("hairdresser", "coiffeur", "divertissement"),
    ("actor", "acteur", "divertissement"),
    ("a stunt", "une cascade / un cascadeur", "divertissement"),
    ("exhibition", "une exposition", "divertissement"),
    ("landscape", "paysage", "divertissement"),
    ("drawing", "dessin", "divertissement"),
    ("painting", "peinture / tableau", "divertissement"),
    ("painter", "peintre", "divertissement"),
    ("guided tour", "visite guidée", "divertissement"),
    ("jewellery", "bijoux", "divertissement"),
    ("sewing", "couture", "divertissement"),
    ("knitting", "tricot", "divertissement"),
    ("baking", "pâtisserie", "divertissement"),
    ("a gig", "un concert", "divertissement"),
    ("to go clubbing", "sortie en boîte", "divertissement"),
    ("a nightclub", "une boîte de nuit", "divertissement"),
    ("to be drunk", "être bourré", "divertissement"),
    ("darts", "les fléchettes", "divertissement"),
    ("to listen to music", "écouter de la musique", "divertissement"),
    ("an amusement park", "un parc d'attraction", "divertissement"),
    ("a rollercoaster", "les montagnes russes", "divertissement"),
    ("a fair", "une foire", "divertissement"),
    ("swimming", "natation", "divertissement"),
    ("a mall / a shopping center", "un centre commercial", "divertissement"),
    ("a suit", "un costume", "divertissement"),
    ("a sweater", "un pull", "divertissement"),
    ("soccer / football", "football", "divertissement"),
    ("clothes", "vêtements", "divertissement"),
    ("a cook", "un cuisinier", "divertissement"),
    ("to afford", "pouvoir s'offrir", "divertissement"),

    # ── Finance / Économie ───────────────────────────────────
    ("GDP", "PIB", "finance"),
    ("economy", "économie", "finance"),
    ("bankruptcy", "faillite", "finance"),
    ("cash", "espèces / liquidités", "finance"),
    ("consumption", "consommation", "finance"),
    ("cost", "coût", "finance"),
    ("currency", "monnaie / devise", "finance"),
    ("deficit", "déficit", "finance"),
    ("deposit", "acompte / dépôt", "finance"),
    ("growth", "croissance", "finance"),
    ("household", "un foyer", "finance"),
    ("interest rate", "taux d'intérêt", "finance"),
    ("purchasing power", "pouvoir d'achat", "finance"),
    ("scarcity", "rareté", "finance"),
    ("shortage", "pénurie", "finance"),
    ("gross", "brut", "finance"),
    ("a merger", "une fusion", "finance"),
    ("advertising", "publicité", "finance"),
    ("accounting", "comptabilité", "finance"),
    ("an accountant", "un comptable", "finance"),
    ("a bank", "une banque", "finance"),
    ("a banker", "un banquier", "finance"),
    ("a mortgage", "un prêt immobilier", "finance"),
    ("a loan", "un prêt", "finance"),
    ("to loan", "prêter", "finance"),
    ("to borrow", "emprunter", "finance"),
    ("a transfer", "un virement", "finance"),
    ("to withdraw money", "retirer de l'argent", "finance"),
    ("a bank account", "un compte bancaire", "finance"),
    ("a bank clerk", "un employé de banque", "finance"),
    ("a credit card", "une carte de crédit", "finance"),
    ("to pay cash", "payer en espèces", "finance"),
    ("savings", "l'épargne", "finance"),
    ("a savings account", "un compte épargne", "finance"),
    ("a checking account", "compte chèque", "finance"),
    ("to save money", "économiser de l'argent", "finance"),
    ("balance sheet", "bilan", "finance"),
    ("liabilities", "dettes / engagements", "finance"),
    ("an asset", "un actif / un atout", "finance"),
    ("to invest", "investir", "finance"),
    ("real estate", "l'immobilier", "finance"),
    ("shareholder", "actionnaire", "finance"),
    ("inheritance", "héritage", "finance"),
    ("compound interest", "intérêt composé", "finance"),
    ("fees", "frais", "finance"),
    ("tax", "taxe / impôt", "finance"),
    ("debt", "la dette", "finance"),
    ("cash flow", "flux de trésorerie", "finance"),
    ("equity", "capitaux propres", "finance"),
    ("ROI", "retour sur investissement", "finance"),
    ("crowdfunding", "financement participatif", "finance"),
    ("a broker", "un courtier", "finance"),
    ("turnover", "le chiffre d'affaires", "finance"),
    ("loss", "pertes", "finance"),
    ("to merge", "fusionner", "finance"),
    ("overdraft", "découvert", "finance"),
    ("the stock exchange", "la bourse", "finance"),
    ("shares", "actions", "finance"),
    ("profit", "le profit", "finance"),
    ("margin", "la marge", "finance"),
    ("hedge fund", "fonds spéculatif", "finance"),
    ("money laundering", "le blanchiment d'argent", "finance"),
    ("a coin", "une pièce", "finance"),
    ("a banknote", "un billet", "finance"),
    ("to grant a loan", "accorder un crédit", "finance"),

    # ── Informatique ─────────────────────────────────────────
    ("computer", "ordinateur", "informatique"),
    ("desktop", "ordinateur de bureau", "informatique"),
    ("laptop", "ordinateur portable", "informatique"),
    ("keyboard", "clavier", "informatique"),
    ("to sign up", "s'inscrire", "informatique"),
    ("a software", "un logiciel", "informatique"),
    ("database", "base de données", "informatique"),
    ("a network", "un réseau", "informatique"),
    ("user interface", "interface utilisateur", "informatique"),
    ("to log in", "se connecter", "informatique"),
    ("to log out", "se déconnecter", "informatique"),
    ("firewall", "pare-feu", "informatique"),
    ("to delete", "effacer / supprimer", "informatique"),
    ("to download", "télécharger", "informatique"),
    ("to update", "mettre à jour", "informatique"),
    ("a file", "un fichier", "informatique"),
    ("a printer", "une imprimante", "informatique"),
    ("a link", "un lien", "informatique"),
    ("to upload", "mettre en ligne", "informatique"),
    ("a user", "un utilisateur", "informatique"),
    ("online", "en ligne", "informatique"),
    ("to attach", "mettre en pièce jointe", "informatique"),
    ("a spreadsheet", "un tableur", "informatique"),
    ("an attachment", "une pièce jointe", "informatique"),
    ("a graph", "un graphique", "informatique"),
    ("to cancel", "annuler", "informatique"),
    ("to click", "cliquer", "informatique"),
    ("a homepage", "une page d'accueil", "informatique"),
    ("memory", "mémoire", "informatique"),
    ("a screen", "un écran", "informatique"),
    ("digital", "numérique", "informatique"),
    ("USB key", "une clé USB", "informatique"),
    ("a mouse", "une souris", "informatique"),
    ("a folder", "un dossier", "informatique"),
    ("to reboot", "redémarrer", "informatique"),
    ("a search engine", "un moteur de recherche", "informatique"),
    ("ink cartridge", "une cartouche d'encre", "informatique"),
    ("a backup", "une sauvegarde", "informatique"),
    ("a password", "mot de passe", "informatique"),
    ("a browser", "un navigateur", "informatique"),
    ("malware", "logiciel malveillant", "informatique"),
    ("troubleshooting", "dépannage", "informatique"),
    ("wireless", "sans fil", "informatique"),
    ("cloud storage", "stockage en ligne", "informatique"),
    ("server", "serveur", "informatique"),
    ("a tab", "un onglet", "informatique"),
    ("an email address", "une adresse mail", "informatique"),
    ("a newsletter", "une lettre d'information", "informatique"),
    ("to register", "s'inscrire", "informatique"),
    ("a username", "un identifiant de connexion", "informatique"),
    ("to forward", "transférer (un mail)", "informatique"),

    # ── Environnement / Météo / Santé ────────────────────────
    ("the weather", "la météo", "environnement"),
    ("the weather forecast", "les prévisions météo", "environnement"),
    ("sunny", "ensoleillé", "environnement"),
    ("cloudy", "nuageux", "environnement"),
    ("rainy", "pluvieux", "environnement"),
    ("snowy", "neigeux", "environnement"),
    ("windy", "venteux", "environnement"),
    ("icy", "glacé", "environnement"),
    ("foggy", "avec du brouillard", "environnement"),
    ("freezing", "gelé / très froid", "environnement"),
    ("warm", "chaud / doux", "environnement"),
    ("a storm", "une tempête", "environnement"),
    ("thunder", "l'orage", "environnement"),
    ("a cloud", "un nuage", "environnement"),
    ("a breeze", "une brise", "environnement"),
    ("unpredictable", "imprévisible", "environnement"),
    ("clear", "sans nuage", "environnement"),
    ("to warn", "prévenir", "environnement"),
    ("chilly", "frisquet / froid", "environnement"),
    ("flood", "inondation", "environnement"),
    ("drought", "sécheresse", "environnement"),
    ("heat wave", "vague de chaleur", "environnement"),
    ("frost", "gel", "environnement"),
    ("mild", "doux", "environnement"),
    ("lightning", "éclair", "environnement"),
    ("partly cloudy", "partiellement couvert", "environnement"),
    ("overcast", "couvert / nuageux", "environnement"),
    ("puddle", "flaque", "environnement"),
    ("rainbow", "arc-en-ciel", "environnement"),
    ("sunshine", "rayon de soleil", "environnement"),
    ("sunset", "coucher de soleil", "environnement"),
    ("sunrise", "lever de soleil", "environnement"),
    ("dawn", "aube", "environnement"),
    ("dusk", "crépuscule", "environnement"),
    ("snowflake", "flocon de neige", "environnement"),
    ("earthquake", "tremblement de terre", "environnement"),
    ("a headache", "un mal de tête", "environnement"),
    ("to work out", "s'entraîner", "environnement"),
    ("harmful", "nuisible", "environnement"),
    ("overweight", "en surpoids", "environnement"),
    ("healthy", "bon pour la santé", "environnement"),
    ("global warming", "réchauffement climatique", "environnement"),
    ("spring", "printemps", "environnement"),
    ("fall / autumn", "automne", "environnement"),
    ("winter", "hiver", "environnement"),
    ("summer", "été", "environnement"),
    ("eco-friendly", "respectueux de l'environnement", "environnement"),
    ("garbage", "déchets", "environnement"),
    ("sick", "malade", "environnement"),
    ("an injury", "une blessure", "environnement"),
    ("to be injured", "être blessé", "environnement"),
    ("disabled", "handicapé", "environnement"),
    ("wheelchair", "chaise roulante", "environnement"),
    ("to recycle", "recycler", "environnement"),
    ("to sort / to declutter", "trier", "environnement"),

    # ── Marketing / Vente ────────────────────────────────────
    ("subscription", "abonnement", "marketing"),
    ("a flyer", "un prospectus", "marketing"),
    ("to launch", "lancer", "marketing"),
    ("membership", "adhésion", "marketing"),
    ("survey", "une enquête", "marketing"),
    ("a form", "un formulaire", "marketing"),
    ("a venue", "un lieu / une salle", "marketing"),
    ("a brochure", "une brochure", "marketing"),
    ("announcement", "une annonce", "marketing"),
    ("an event", "un événement", "marketing"),
    ("available", "disponible", "marketing"),
    ("a brand", "une marque", "marketing"),
    ("a speech", "un discours", "marketing"),
    ("a bargain", "une bonne affaire", "marketing"),
    ("sustainable", "durable", "marketing"),
    ("guarantee", "une garantie", "marketing"),
    ("to retail", "vente au détail", "marketing"),
    ("wholesale", "en gros", "marketing"),
    ("to sell", "vendre", "marketing"),
    ("to buy / to purchase", "acheter", "marketing"),
    ("to pay back", "rembourser", "marketing"),
    ("a coupon", "un bon d'achat", "marketing"),
    ("sales", "les soldes", "marketing"),
    ("for sale", "en vente", "marketing"),
    ("to rent", "louer", "marketing"),
    ("upscale", "haut de gamme", "marketing"),
    ("a sample", "un échantillon", "marketing"),
    ("packaging", "emballage / conditionnement", "marketing"),
    ("storage", "stockage", "marketing"),
    ("shipping", "transport / expédition", "marketing"),
    ("delivery", "livraison", "marketing"),
    ("a shop / a store", "un magasin", "marketing"),
    ("money back guarantee", "satisfait ou remboursé", "marketing"),
    ("features", "caractéristiques", "marketing"),
    ("competitors", "les concurrents", "marketing"),
    ("the competition", "la concurrence", "marketing"),

    # ── Voyage ───────────────────────────────────────────────
    ("a journey", "un voyage / un trajet", "voyage"),
    ("location", "lieu", "voyage"),
    ("to go sightseeing", "faire du tourisme", "voyage"),
    ("a view", "une vue", "voyage"),
    ("to travel", "voyager", "voyage"),
    ("to stay", "rester / séjourner", "voyage"),
    ("to postpone", "reporter à plus tard", "voyage"),
    ("to book", "réserver", "voyage"),
    ("a booking", "une réservation", "voyage"),
    ("holiday / vacation", "vacances", "voyage"),
    ("a trip", "un séjour / un trajet", "voyage"),
    ("a campsite", "un camping", "voyage"),
    ("a motor home", "un camping-car", "voyage"),
    ("a flight", "un vol", "voyage"),
    ("a boarding pass", "une carte d'embarquement", "voyage"),
    ("to check in", "enregistrer ses bagages", "voyage"),
    ("luggage / baggage", "bagages", "voyage"),
    ("to pack / unpack your bag", "faire / défaire son sac", "voyage"),
    ("to take off", "décoller", "voyage"),
    ("to land", "atterrir", "voyage"),
    ("to pick up someone", "aller chercher quelqu'un", "voyage"),
    ("to drop off someone", "déposer quelqu'un", "voyage"),
    ("to be delayed", "être en retard", "voyage"),
    ("the gate", "la porte d'embarquement", "voyage"),
    ("an aisle seat", "un siège côté couloir", "voyage"),
    ("a carry-on", "un sac cabine", "voyage"),
    ("a connection", "une correspondance", "voyage"),
    ("a complimentary meal", "un repas offert", "voyage"),
    ("a bumpy flight", "un vol avec des turbulences", "voyage"),
    ("an ID card", "une carte d'identité", "voyage"),
    ("to be free of charge", "être gratuit", "voyage"),
    ("to fasten the seat belt", "attacher la ceinture", "voyage"),
    ("a return ticket", "un billet aller-retour", "voyage"),
    ("a one way ticket", "un billet aller simple", "voyage"),
    ("rush hour", "l'heure de pointe", "voyage"),
    ("package holiday", "vacances à forfait", "voyage"),
    ("a cruise", "une croisière", "voyage"),
    ("a cruise ship", "un bateau de croisière", "voyage"),
    ("an ATM / a cash machine", "un distributeur automatique de billets", "voyage"),
    ("to be fully booked", "être complet", "voyage"),
    ("a single room", "une chambre simple", "voyage"),
    ("to pay upfront", "payer à l'avance", "voyage"),
    ("a locker", "un casier", "voyage"),
    ("a safe", "un coffre-fort", "voyage"),
    ("air conditioning / AC", "la climatisation", "voyage"),
    ("a kettle", "une bouilloire", "voyage"),
    ("a dorm", "un dortoir", "voyage"),
    ("drivers licence", "permis de conduire", "voyage"),
    ("a backpack / a rucksack", "un sac à dos", "voyage"),
    ("a receipt", "un reçu / ticket de caisse", "voyage"),
    ("souvenirs", "des souvenirs", "voyage"),
    ("unforgettable", "inoubliable", "voyage"),
    ("crowded", "bondé", "voyage"),
    ("touristy", "touristique", "voyage"),
    ("to have a good time", "passer un bon moment", "voyage"),
    ("to rest", "se reposer", "voyage"),
    ("to be homesick", "avoir le mal du pays", "voyage"),
    ("a guided tour", "une visite guidée", "voyage"),
    ("a map", "une carte", "voyage"),
    ("the subway", "le métro", "voyage"),
    ("a cab / a taxi", "un taxi", "voyage"),
    ("the train station", "la gare", "voyage"),
    ("the platform", "le quai", "voyage"),
    ("to hike", "faire de la randonnée", "voyage"),
    ("passport", "passeport", "voyage"),
    ("visa", "visa", "voyage"),
    ("customs", "douane", "voyage"),
    ("car rental", "voiture de location", "voyage"),

    # ── Industrie / Transport / Logistique ───────────────────
    ("the supply chain", "la chaîne logistique", "industrie"),
    ("inventory", "l'inventaire", "industrie"),
    ("container", "conteneur", "industrie"),
    ("hub", "plateforme logistique", "industrie"),
    ("inventory shortage", "rupture de stock", "industrie"),
    ("lot number", "numéro de lot", "industrie"),
    ("order backlog", "carnet de commandes", "industrie"),
    ("racking", "rayonnage", "industrie"),
    ("shipping center", "centre d'expédition", "industrie"),
    ("stock management", "gestion des stocks", "industrie"),
    ("warehouse", "entrepôt", "industrie"),
    ("pallet rack", "palettier", "industrie"),
    ("to ship", "expédier", "industrie"),
    ("to deliver", "livrer", "industrie"),
    ("delay", "retard", "industrie"),
    ("a package", "un colis", "industrie"),
    ("to store", "entreposer", "industrie"),
    ("to handle", "manutentionner", "industrie"),
    ("to stack containers", "empiler les conteneurs", "industrie"),
    ("to receive", "réceptionner", "industrie"),
    ("to load", "charger", "industrie"),
    ("to unload", "décharger", "industrie"),
    ("aisle", "allée de circulation", "industrie"),
    ("technical specifications", "cahier des charges", "industrie"),
    ("goods", "marchandise", "industrie"),
    ("item", "article", "industrie"),
    ("delivery order / note", "bon de livraison", "industrie"),
    ("shipper", "chargeur / expéditeur", "industrie"),
    ("bar code", "code-barres", "industrie"),
    ("trailer", "remorque", "industrie"),
    ("logistics", "logistique", "industrie"),
    ("supplier / provider", "fournisseur", "industrie"),
    ("delivery date", "date de livraison", "industrie"),
    ("duties", "droit de douane", "industrie"),
    ("freight", "fret", "industrie"),
    ("out of stock", "en rupture de stock", "industrie"),
    ("upstream", "en amont", "industrie"),
    ("downstream", "en aval", "industrie"),
    ("requirements", "besoins", "industrie"),
    ("a truck / a lorry", "un camion", "industrie"),

    # ── Faux amis ────────────────────────────────────────────
    ("an ability", "une aptitude", "faux amis"),
    ("to abuse", "insulter", "faux amis"),
    ("to achieve", "réaliser", "faux amis"),
    ("actually", "en fait", "faux amis"),
    ("to address", "aborder un problème / une question", "faux amis"),
    ("ancient", "antique / très ancien", "faux amis"),
    ("to annoy", "irriter", "faux amis"),
    ("to assist", "aider", "faux amis"),
    ("to assume", "supposer / assumer", "faux amis"),
    ("to balance", "tenir en équilibre / équilibrer", "faux amis"),
    ("barracks", "caserne", "faux amis"),
    ("basic", "essentiel / fondamental", "faux amis"),
    ("a benefit", "un avantage", "faux amis"),
    ("a bribe", "un pot-de-vin", "faux amis"),
    ("candid", "sincère", "faux amis"),
    ("caution", "prudence", "faux amis"),
    ("chance", "hasard", "faux amis"),
    ("a character", "un personnage", "faux amis"),
    ("to charge", "faire payer", "faux amis"),
    ("a chip", "une frite / une puce électronique", "faux amis"),
    ("a college", "une université", "faux amis"),
    ("a commodity", "une marchandise", "faux amis"),
    ("a compass", "une boussole", "faux amis"),
    ("to complete", "terminer / achever", "faux amis"),
    ("complimentary", "gratuit / complémentaire", "faux amis"),
    ("comprehensive", "complet", "faux amis"),
    ("a conductor", "un contrôleur", "faux amis"),
    ("confidence", "confiance", "faux amis"),
    ("to consign", "expédier", "faux amis"),
    ("to contemplate", "envisager", "faux amis"),
    ("content", "contenu / satisfait", "faux amis"),
    ("a copy", "un exemplaire / une photocopie", "faux amis"),
    ("countenance", "expression du visage", "faux amis"),
    ("a crayon", "un crayon de couleur", "faux amis"),
    ("a critic", "un critique d'art / littéraire", "faux amis"),
    ("to cry", "pleurer", "faux amis"),
    ("a curator", "un commissaire d'exposition", "faux amis"),
    ("to deceive", "tromper / duper", "faux amis"),
    ("definitely", "à coup sûr / sans aucun doute", "faux amis"),
    ("to demand", "exiger", "faux amis"),
    ("a demonstration", "une manifestation", "faux amis"),
    ("to deserve", "mériter", "faux amis"),
    ("to deter", "dissuader", "faux amis"),
    ("a directory", "un annuaire", "faux amis"),
    ("to dispose", "se débarrasser", "faux amis"),
    ("disposable", "jetable", "faux amis"),
    ("a dispute", "un conflit", "faux amis"),
    ("distracted", "fou / égaré", "faux amis"),
    ("dramatic", "spectaculaire", "faux amis"),
    ("engaged", "occupé / fiancé", "faux amis"),
    ("estate", "domaine", "faux amis"),
    ("evidence", "preuves / témoignage", "faux amis"),
    ("eventually", "finalement", "faux amis"),
    ("expertise", "compétence", "faux amis"),
    ("extra", "supplémentaire", "faux amis"),
    ("fabric", "tissu", "faux amis"),
    ("faculty", "le personnel enseignant / faculté", "faux amis"),
    ("a figure", "une silhouette", "faux amis"),
    ("fortunate", "chanceux", "faux amis"),
    ("furnished", "meublé", "faux amis"),
    ("gas", "essence / gaz", "faux amis"),
    ("gentle", "aimable / doux", "faux amis"),
    ("grand", "grandiose", "faux amis"),
    ("grapes", "raisin", "faux amis"),
    ("to grate", "râper / grincer", "faux amis"),
    ("a groom", "jeune marié / palefrenier", "faux amis"),
    ("a habit", "une habitude", "faux amis"),
    ("hazardous", "dangereux", "faux amis"),
    ("to hurt", "(se) blesser", "faux amis"),
    ("to imply", "sous-entendre / impliquer", "faux amis"),
    ("inconvenient", "inopportun", "faux amis"),
    ("to indulge", "se laisser aller", "faux amis"),
    ("invaluable", "inestimable", "faux amis"),
    ("isolation", "isolement", "faux amis"),
    ("an issue", "un problème / une question", "faux amis"),
    ("large", "grand", "faux amis"),
    ("a lecture", "une conférence", "faux amis"),
    ("a location", "un lieu / un emplacement", "faux amis"),
    ("to maintain", "entretenir / maintenir", "faux amis"),
    ("to march", "défiler", "faux amis"),
    ("a medicine", "un médicament", "faux amis"),
    ("mercy", "pitié / miséricorde", "faux amis"),
    ("a nap", "une sieste", "faux amis"),
    ("a notice", "un avis / un préavis", "faux amis"),
    ("to notice", "remarquer", "faux amis"),
    ("a novel", "un roman", "faux amis"),
    ("a nurse", "une infirmière", "faux amis"),
    ("a partition", "une séparation", "faux amis"),
    ("to pass an exam", "réussir un examen", "faux amis"),
    ("a patron", "un client", "faux amis"),
    ("petrol", "essence", "faux amis"),
    ("a photograph", "une photographie", "faux amis"),
    ("a phrase", "une expression / une locution", "faux amis"),
    ("a physician", "un médecin", "faux amis"),
    ("a pipe", "un tuyau / une pipe", "faux amis"),
    ("a place", "un endroit", "faux amis"),
    ("to pretend", "faire semblant", "faux amis"),
    ("preservative", "un conservateur alimentaire", "faux amis"),
    ("to prevent", "empêcher", "faux amis"),
    ("proper", "adéquat", "faux amis"),
    ("a queue", "une file d'attente", "faux amis"),
    ("a recipient", "un destinataire / un bénéficiaire", "faux amis"),
    ("to recover", "se rétablir", "faux amis"),
    ("refuse", "déchets", "faux amis"),
    ("to regard", "considérer", "faux amis"),
    ("regular", "normal / régulier", "faux amis"),
    ("to relieve", "soulager", "faux amis"),
    ("to report", "faire un rapport", "faux amis"),
    ("to resume", "reprendre après une pause", "faux amis"),
    ("to retain", "garder / conserver", "faux amis"),
    ("reunion", "retrouvailles", "faux amis"),
    ("rude", "grossier", "faux amis"),
    ("Scotch", "whisky", "faux amis"),
    ("sensible", "sensé / raisonnable", "faux amis"),
    ("a socket", "une prise de courant / une douille", "faux amis"),
    ("a square", "une place / un square", "faux amis"),
    ("a stage", "une étape / une scène", "faux amis"),
    ("stationery", "papeterie / fournitures de bureau", "faux amis"),
    ("a store", "un grand magasin", "faux amis"),
    ("supplies", "fournitures", "faux amis"),
    ("to support", "soutenir", "faux amis"),
    ("a surname", "un nom de famille", "faux amis"),
    ("to survey", "examiner", "faux amis"),
    ("sympathetic", "compatissant", "faux amis"),
    ("a tap", "un robinet", "faux amis"),
    ("tape", "du scotch / une cassette / une bande", "faux amis"),
    ("a tissue", "un mouchoir", "faux amis"),
    ("touchy", "susceptible", "faux amis"),
    ("a tour", "un circuit", "faux amis"),
    ("a trade union", "un syndicat", "faux amis"),
    ("a trap", "un piège", "faux amis"),
    ("to use", "utiliser", "faux amis"),
    ("vacation", "vacances", "faux amis"),
    ("valid", "valable", "faux amis"),
    ("valuable", "de valeur / précieux", "faux amis"),
    ("versatile", "polyvalent", "faux amis"),
    ("a vest", "un gilet (US) / un maillot de corps (UK)", "faux amis"),
    ("virtually", "quasiment / presque", "faux amis"),

    # ── Nouveau vocabulaire enrichi ──────────────────────────
    ("an advertisement", "une publicité", "marketing"),
    ("to advertise / to promote", "faire de la publicité / promouvoir", "verbes"),
    ("an agenda", "un ordre du jour / un programme", "communication"),
    ("to agree with", "être d'accord avec", "verbes"),
    ("to agree on", "s'accorder sur", "verbes"),
    ("a bid", "une enchère / une offre", "finance"),
    ("a bill", "une facture / une addition / un billet", "finance"),
    ("the blueprints", "un projet / un plan", "industrie"),
    ("to check", "vérifier", "verbes"),
    ("commuting", "le trajet domicile-travail", "emploi"),
    ("current", "actuel(le)", "général"),
    ("the damage", "les dégâts", "général"),
    ("the facilities", "les installations / les équipements", "emploi"),
    ("the furniture", "le mobilier", "objets"),
    ("the guidelines", "les directives / les recommandations", "emploi"),
    ("the hazard", "le danger / le risque", "général"),
    ("law", "la loi", "général"),
    ("a lawyer", "un avocat", "métiers"),
    ("to lay off / to dismiss", "licencier", "verbes"),
    ("a leak", "une fuite (de liquide)", "objets"),
    ("an owner / a proprietor", "un propriétaire", "emploi"),
    ("the premises", "les locaux d'une entreprise", "emploi"),
    ("to process", "traiter", "verbes"),
    ("to provide", "fournir", "verbes"),
    ("the purpose / the goal / the aim", "le but", "général"),
    ("a quote / a quotation", "un devis", "emploi"),
    ("a rate", "un tarif / un taux", "finance"),
    ("to require", "exiger", "verbes"),
    ("a retail store", "un magasin de vente au détail", "marketing"),
    ("a shipment", "une expédition / une cargaison", "industrie"),
    ("a submission", "une proposition soumise à une autorité", "emploi"),
    ("to subscribe", "s'abonner", "marketing"),
    ("the staff / the personnel", "le personnel", "emploi"),
    ("to fund / to finance", "financer", "verbes"),
    ("an application", "une candidature", "emploi"),
    ("the assets", "les liquidités / les avoirs", "finance"),
    ("the Board of Directors", "le conseil d'administration", "emploi"),

    # ── Objets du quotidien ──────────────────────────────────
    ("appliance", "appareil électroménager", "objets"),
    ("apron", "tablier", "objets"),
    ("baby carriage / pram", "landau", "objets"),
    ("bag", "sac", "objets"),
    ("bench", "banc", "objets"),
    ("board", "tableau (blanc / d'affichage)", "objets"),
    ("bookcase", "bibliothèque (meuble)", "objets"),
    ("booklet", "fascicule", "objets"),
    ("briefcase", "mallette", "objets"),
    ("cabinet", "meuble de rangement", "objets"),
    ("carpet / rug", "tapis", "objets"),
    ("chair", "chaise", "objets"),
    ("chart", "graphique", "objets"),
    ("clippers", "tondeuse à cheveux", "objets"),
    ("coal", "charbon", "objets"),
    ("conveyor belt", "tapis roulant", "objets"),
    ("counter", "comptoir", "objets"),
    ("crane", "grue", "objets"),
    ("cupboard", "placard", "objets"),
    ("drill", "perceuse", "objets"),
    ("elevator / lift", "ascenseur", "objets"),
    ("equipment", "équipement", "objets"),
    ("filing cabinet", "meuble de classement", "objets"),
    ("forklift", "chariot élévateur", "objets"),
    ("gloves", "gants", "objets"),
    ("guardrail", "glissière de sécurité", "objets"),
    ("heating", "chauffage", "objets"),
    ("helmet / hard hat", "casque", "objets"),
    ("hose", "tuyau d'arrosage", "objets"),
    ("ladder", "échelle", "objets"),
    ("lawnmower", "tondeuse à gazon", "objets"),
    ("menu", "carte au restaurant", "objets"),
    ("package / parcel", "paquet / colis", "objets"),
    ("phone directory", "annuaire téléphonique", "objets"),
    ("rope", "corde", "objets"),
    ("scale / scales", "balance", "objets"),
    ("shopping cart / trolley", "caddie", "objets"),
    ("sign", "panneau de signalisation", "objets"),
    ("sink", "évier", "objets"),
    ("sled / sledge", "luge", "objets"),
    ("slot", "case / fente / créneau", "objets"),
    ("spare part", "pièce de rechange", "objets"),
    ("stain", "tache", "objets"),
    ("stapler", "agrafeuse", "objets"),
    ("steel barrel", "baril en acier", "objets"),
    ("stretcher", "civière / brancard", "objets"),
    ("stroller / pushchair", "poussette", "objets"),
    ("tablecloth", "nappe", "objets"),
    ("tire / tyre", "pneu", "objets"),
    ("tool", "outil", "objets"),
    ("trolley", "chariot", "objets"),
    ("vacuum cleaner", "aspirateur", "objets"),
    ("vending machine", "distributeur automatique de nourriture", "objets"),
    ("wallet", "portefeuille", "objets"),
    ("wheelbarrow", "brouette", "objets"),

    # ── Métiers / Professions ────────────────────────────────
    ("architect", "architecte", "métiers"),
    ("baker", "boulanger", "métiers"),
    ("bellman", "groom", "métiers"),
    ("carmaker", "fabricant de voitures", "métiers"),
    ("carrier", "transporteur", "métiers"),
    ("cashier", "caissier", "métiers"),
    ("caterer", "traiteur", "métiers"),
    ("ceo", "PDG", "métiers"),
    ("chef", "chef cuisinier", "métiers"),
    ("cleaners", "teinturier", "métiers"),
    ("concierge", "réceptionniste", "métiers"),
    ("dealer", "revendeur / commerçant", "métiers"),
    ("doorman", "portier", "métiers"),
    ("driver", "chauffeur / conducteur", "métiers"),
    ("firefighter / fireman", "pompier", "métiers"),
    ("flight attendant", "hôtesse de l'air / steward", "métiers"),
    ("handler", "manutentionnaire", "métiers"),
    ("hotel clerk", "employé d'hôtel", "métiers"),
    ("jeweller / jeweler", "bijoutier", "métiers"),
    ("lecturer", "maître de conférence", "métiers"),
    ("mailman", "postier", "métiers"),
    ("mechanic", "mécanicien", "métiers"),
    ("pilot", "pilote", "métiers"),
    ("plumber", "plombier", "métiers"),
    ("real estate agent", "agent immobilier", "métiers"),
    ("repairman", "réparateur", "métiers"),
    ("secretary", "secrétaire", "métiers"),
    ("teller", "guichetier", "métiers"),

    # ── Lieux ────────────────────────────────────────────────
    ("bookshop", "librairie", "lieux"),
    ("bridge / overpass", "pont", "lieux"),
    ("cafeteria", "cafétéria / cantine", "lieux"),
    ("cellar", "cave", "lieux"),
    ("conference hall", "salle de conférence", "lieux"),
    ("construction site / work site", "chantier", "lieux"),
    ("department store / supermarket", "supermarché / grand magasin", "lieux"),
    ("diner", "restaurant américain", "lieux"),
    ("factory / plant", "usine", "lieux"),
    ("garden", "jardin", "lieux"),
    ("gas station / petrol station", "station-essence", "lieux"),
    ("laboratory", "laboratoire", "lieux"),
    ("lane", "voie", "lieux"),
    ("lawn", "pelouse", "lieux"),
    ("library", "bibliothèque", "lieux"),
    ("lobby", "hall d'hôtel", "lieux"),
    ("newsstand", "kiosque à journaux", "lieux"),
    ("sidewalk", "trottoir", "lieux"),
    ("toll booth", "péage", "lieux"),
    ("walkway", "passage piéton", "lieux"),

    # ── Vêtements / Accessoires ──────────────────────────────
    ("backpack", "sac à dos", "vêtements"),
    ("cap", "casquette", "vêtements"),
    ("garment", "vêtement", "vêtements"),
    ("glasses", "lunettes", "vêtements"),
    ("hat", "chapeau", "vêtements"),
    ("jacket", "veste", "vêtements"),
    ("long-sleeved", "à manches longues", "vêtements"),
    ("outfit", "tenue", "vêtements"),
    ("overalls", "combinaison de travail", "vêtements"),
    ("purse", "sac à main", "vêtements"),
    ("shirt", "chemise", "vêtements"),
    ("short-sleeved", "à manches courtes", "vêtements"),
    ("suitcase", "valise", "vêtements"),
    ("sunglasses", "lunettes de soleil", "vêtements"),
    ("tie", "cravate", "vêtements"),
    ("white coat / lab coat", "blouse blanche", "vêtements"),

    # ── Transport / Circulation ──────────────────────────────
    ("highway", "autoroute", "transport"),
    ("shuttle", "navette", "transport"),
    ("traffic lights", "feu de signalisation", "transport"),
    ("a vehicle", "un véhicule", "transport"),
    ("public transport", "les transports en commun", "transport"),
    ("a subway / an underground", "le métro", "transport"),
    ("a platform", "le quai", "transport"),
    ("a railway / a railroad", "la voie ferrée", "transport"),
    ("a fare", "le prix du billet", "transport"),
    ("a timetable / a schedule", "les horaires", "transport"),
    ("a delay", "un retard", "transport"),
    ("a roundabout", "un rond-point", "transport"),
    ("a traffic jam", "un embouteillage", "transport"),
    ("a pedestrian", "un piéton", "transport"),
    ("a crosswalk / a pedestrian crossing", "un passage piéton", "transport"),
    ("a lane", "une voie de circulation", "transport"),
    ("a toll", "le péage", "transport"),
    ("a parking lot / a car park", "un parking", "transport"),
    ("fuel", "le carburant", "transport"),
    ("a cyclist", "un cycliste", "transport"),
    ("a detour", "une déviation", "transport"),
    ("a breakdown", "une panne", "transport"),
    ("a tow truck", "une dépanneuse", "transport"),
    ("a seatbelt", "une ceinture de sécurité", "transport"),
    ("a license plate", "une plaque d'immatriculation", "transport"),
    ("a speed limit", "la limitation de vitesse", "transport"),
    ("a one-way street", "une rue à sens unique", "transport"),
    ("a dead end", "une impasse", "transport"),
    ("an intersection / a junction", "un carrefour", "transport"),
    ("a ferry", "un ferry", "transport"),
    ("a freight train", "un train de marchandises", "transport"),
    ("cargo", "une cargaison", "transport"),
    ("a parking space", "une place de parking", "transport"),
    ("to refuel", "faire le plein", "transport"),
    ("roadworks", "des travaux routiers", "transport"),
    ("a bus stop", "un arrêt de bus", "transport"),
    ("a passenger", "un passager", "transport"),
    ("a fleet", "une flotte (de véhicules)", "transport"),

    # ── Communication ────────────────────────────────────────
    ("a phone call", "un appel téléphonique", "communication"),
    ("a voicemail", "un message vocal", "communication"),
    ("a conference call", "une conférence téléphonique", "communication"),
    ("the minutes", "le compte rendu / le procès-verbal", "communication"),
    ("a memo", "une note de service", "communication"),
    ("a survey", "un sondage / une enquête", "communication"),
    ("feedback", "le retour / les commentaires", "communication"),
    ("an announcement", "une annonce", "communication"),
    ("a press release", "un communiqué de presse", "communication"),
    ("a spokesperson", "un porte-parole", "communication"),
    ("a sender", "un expéditeur", "communication"),
    ("to reply", "répondre", "communication"),
    ("a reminder", "un rappel", "communication"),
    ("a notice board / a bulletin board", "un panneau d'affichage", "communication"),
    ("small talk", "une conversation informelle", "communication"),
    ("a misunderstanding", "un malentendu", "communication"),
    ("to keep in touch", "rester en contact", "communication"),
    ("to get in touch", "prendre contact", "communication"),
    ("a follow-up", "un suivi", "communication"),
    ("an inquiry / an enquiry", "une demande de renseignements", "communication"),
    ("to report to someone", "rendre compte à quelqu'un", "communication"),
    ("a briefing", "une réunion d'information", "communication"),
    ("a handout", "un document distribué", "communication"),
    ("a brochure / a leaflet", "une brochure / un dépliant", "communication"),
    ("to notify", "notifier / informer", "communication"),
    ("to acknowledge receipt", "accuser réception", "communication"),
    ("an interpreter", "un interprète", "communication"),
    ("body language", "le langage corporel", "communication"),
    ("a switchboard", "un standard téléphonique", "communication"),
    ("an extension", "un poste téléphonique", "communication"),
    ("a draft", "un brouillon", "communication"),
    ("a cover letter", "une lettre de motivation", "communication"),
    ("a questionnaire", "un questionnaire", "communication"),
    ("a postponement", "un report", "communication"),
    ("an envelope", "une enveloppe", "communication"),

    # ── Verbes ───────────────────────────────────────────────
    ("to accommodate", "loger", "verbes"),
    ("to attend", "assister à", "verbes"),
    ("to board", "monter à bord", "verbes"),
    ("to brake", "freiner", "verbes"),
    ("to buy / to purchase", "acheter", "verbes"),
    ("to call at", "faire escale à", "verbes"),
    ("to carry", "porter (un poids)", "verbes"),
    ("to cast a shadow", "jeter une ombre", "verbes"),
    ("to check-in", "enregistrer ses bagages", "verbes"),
    ("to chop", "hacher", "verbes"),
    ("to clear", "ranger", "verbes"),
    ("to climb", "grimper", "verbes"),
    ("to convey", "transporter", "verbes"),
    ("to cook", "cuisiner", "verbes"),
    ("to cross", "traverser", "verbes"),
    ("to dig", "creuser", "verbes"),
    ("to display / to exhibit", "exposer", "verbes"),
    ("to draw", "tirer / dessiner", "verbes"),
    ("to empty", "vider", "verbes"),
    ("to fall", "tomber", "verbes"),
    ("to feed", "nourrir", "verbes"),
    ("to fill (in)", "remplir", "verbes"),
    ("to fix / to mend / to repair", "réparer", "verbes"),
    ("to focus", "se concentrer", "verbes"),
    ("to fold", "plier", "verbes"),
    ("to gaze", "regarder avec insistance", "verbes"),
    ("to get off", "sortir de / descendre de", "verbes"),
    ("to gush", "jaillir", "verbes"),
    ("to hand somebody something", "tendre quelque chose à quelqu'un", "verbes"),
    ("to hang up", "raccrocher (le téléphone)", "verbes"),
    ("to hang", "pendre / suspendre / accrocher", "verbes"),
    ("to hit", "frapper / heurter", "verbes"),
    ("to hold", "tenir", "verbes"),
    ("to leak", "fuir (liquide)", "verbes"),
    ("to make a call", "passer un appel téléphonique", "verbes"),
    ("to make a copy", "faire une photocopie", "verbes"),
    ("to overlook", "négliger / ignorer", "verbes"),
    ("to overtake", "doubler (sur la route)", "verbes"),
    ("to pick somebody up", "passer prendre quelqu'un", "verbes"),
    ("to pick something up", "ramasser quelque chose", "verbes"),
    ("to pick up the phone", "décrocher (le téléphone)", "verbes"),
    ("to point to / at something", "pointer quelque chose du doigt", "verbes"),
    ("to pour", "verser", "verbes"),
    ("to raise one's hand", "lever la main", "verbes"),
    ("to sail", "naviguer", "verbes"),
    ("to service", "faire la maintenance", "verbes"),
    ("to set the table", "mettre la table", "verbes"),
    ("to shake hands", "se serrer la main", "verbes"),
    ("to sign", "signer", "verbes"),
    ("to sink", "couler / sombrer", "verbes"),
    ("to sit down", "s'asseoir", "verbes"),
    ("to sit", "être assis", "verbes"),
    ("to skid", "déraper", "verbes"),
    ("to slide", "glisser", "verbes"),
    ("to sort", "trier", "verbes"),
    ("to stack", "empiler", "verbes"),
    ("to stand up", "se lever", "verbes"),
    ("to stand", "être debout", "verbes"),
    ("to sweep", "balayer", "verbes"),
    ("to tower over / to overlook", "surplomber / dominer", "verbes"),
    ("to try on", "essayer (un vêtement)", "verbes"),
    ("to type", "taper à l'ordinateur", "verbes"),
    ("to wave", "faire signe de la main", "verbes"),
    ("to wear", "porter (un vêtement / accessoire)", "verbes"),
    ("to withdraw", "retirer", "verbes"),
    ("to write", "écrire", "verbes"),

    # ── Complément général ──
    ("unavailable", "indisponible", "général"),
    ("a requirement", "une exigence", "général"),
    ("mandatory / compulsory", "obligatoire", "général"),
    ("optional", "facultatif", "général"),
    ("a drawback", "un inconvénient", "général"),
    ("a feature", "une caractéristique", "général"),
    ("a goal", "un but / un objectif", "général"),
    ("an outcome", "un résultat / une issue", "général"),
    ("a trend", "une tendance", "général"),
    ("an estimate", "une estimation", "général"),
    ("a range", "une gamme / une fourchette", "général"),
    ("an attempt", "une tentative", "général"),
    ("a concern", "une préoccupation", "général"),
    ("a priority", "une priorité", "général"),
    ("a guideline", "une directive", "général"),
    ("a procedure", "une procédure", "général"),
    ("a standard", "une norme", "général"),
    ("an improvement", "une amélioration", "général"),
    ("a shortage", "une pénurie", "général"),
    ("a surplus", "un surplus / un excédent", "général"),
    ("a warranty / a guarantee", "une garantie", "général"),
    ("regardless", "indépendamment", "général"),
    ("nevertheless", "néanmoins", "général"),
    ("therefore", "par conséquent", "général"),
    ("meanwhile", "pendant ce temps", "général"),
    ("whereas", "tandis que", "général"),
    ("furthermore", "de plus", "général"),
    ("approximately", "environ", "général"),
    ("accurate", "exact / précis", "général"),
    ("reliable", "fiable", "général"),
    ("efficient", "efficace", "général"),
    ("convenient", "pratique / commode", "général"),
    ("relevant", "pertinent", "général"),
    ("significant", "important / significatif", "général"),
    ("appropriate", "approprié", "général"),
    ("previous", "précédent", "général"),
    ("upcoming", "à venir / prochain", "général"),
    ("entire", "entier", "général"),
    ("various", "divers", "général"),
    ("several", "plusieurs", "général"),
    ("likely", "probable", "général"),
    ("unlikely", "peu probable", "général"),
    ("willing to", "disposé à", "général"),
    ("in charge of", "responsable de", "général"),
    ("on behalf of", "au nom de", "général"),
    ("in advance", "à l'avance", "général"),
    ("as soon as possible", "dès que possible", "général"),
    ("on time", "à l'heure", "général"),
    ("ahead of schedule", "en avance sur le planning", "général"),
    ("behind schedule", "en retard sur le planning", "général"),
    ("up to date", "à jour", "général"),
    ("out of date", "périmé / dépassé", "général"),
    ("by the way", "au fait", "général"),
    ("to be aware of", "être conscient de", "général"),
    ("to deal with", "gérer / traiter", "général"),

    # ── Complément vêtements ──
    ("a shirt", "une chemise", "vêtements"),
    ("a T-shirt", "un t-shirt", "vêtements"),
    ("trousers / pants", "un pantalon", "vêtements"),
    ("jeans", "un jean", "vêtements"),
    ("a skirt", "une jupe", "vêtements"),
    ("a dress", "une robe", "vêtements"),
    ("a jacket", "une veste", "vêtements"),
    ("a coat", "un manteau", "vêtements"),
    ("a sweater / a jumper", "un pull", "vêtements"),
    ("a hoodie", "un sweat à capuche", "vêtements"),
    ("shorts", "un short", "vêtements"),
    ("socks", "des chaussettes", "vêtements"),
    ("shoes", "des chaussures", "vêtements"),
    ("boots", "des bottes", "vêtements"),
    ("sneakers / trainers", "des baskets", "vêtements"),
    ("sandals", "des sandales", "vêtements"),
    ("a hat", "un chapeau", "vêtements"),
    ("a cap", "une casquette", "vêtements"),
    ("a scarf", "une écharpe", "vêtements"),
    ("a belt", "une ceinture", "vêtements"),
    ("a blouse", "un chemisier", "vêtements"),
    ("a uniform", "un uniforme", "vêtements"),
    ("a raincoat", "un imperméable", "vêtements"),
    ("an umbrella", "un parapluie", "vêtements"),
    ("a pocket", "une poche", "vêtements"),
    ("a button", "un bouton", "vêtements"),
    ("a zipper / a zip", "une fermeture éclair", "vêtements"),
    ("a collar", "un col", "vêtements"),
    ("a sleeve", "une manche", "vêtements"),
    ("a size", "une taille", "vêtements"),
    ("a fitting room", "une cabine d'essayage", "vêtements"),
    ("to get dressed", "s'habiller", "vêtements"),
    ("an outfit", "une tenue", "vêtements"),
    ("casual wear", "tenue décontractée", "vêtements"),
    ("formal wear", "tenue habillée", "vêtements"),
    ("jewelry", "des bijoux", "vêtements"),
    ("a ring", "une bague", "vêtements"),
    ("a necklace", "un collier", "vêtements"),
    ("a bracelet", "un bracelet", "vêtements"),
    ("a watch", "une montre", "vêtements"),
    ("a wallet", "un portefeuille", "vêtements"),
    ("a backpack", "un sac à dos", "vêtements"),
    ("cotton", "le coton", "vêtements"),
    ("wool", "la laine", "vêtements"),

    # ── Complément lieux ──
    ("a branch", "une succursale", "lieux"),
    ("a warehouse", "un entrepôt", "lieux"),
    ("a factory / a plant", "une usine", "lieux"),
    ("an office", "un bureau", "lieux"),
    ("a meeting room", "une salle de réunion", "lieux"),
    ("a lobby", "un hall d'entrée", "lieux"),
    ("a conference room", "une salle de conférence", "lieux"),
    ("a stadium", "un stade", "lieux"),
    ("a gym", "une salle de sport", "lieux"),
    ("a library", "une bibliothèque", "lieux"),
    ("a museum", "un musée", "lieux"),
    ("a gallery", "une galerie", "lieux"),
    ("a theater / a theatre", "un théâtre", "lieux"),
    ("a cinema / a movie theater", "un cinéma", "lieux"),
    ("a cafeteria", "une cantine", "lieux"),
    ("a hotel", "un hôtel", "lieux"),
    ("a hospital", "un hôpital", "lieux"),
    ("a clinic", "une clinique", "lieux"),
    ("a pharmacy / a drugstore", "une pharmacie", "lieux"),
    ("a post office", "un bureau de poste", "lieux"),
    ("a city hall / a town hall", "une mairie", "lieux"),
    ("a courthouse", "un palais de justice", "lieux"),
    ("a police station", "un commissariat", "lieux"),
    ("a fire station", "une caserne de pompiers", "lieux"),
    ("a harbor / a port", "un port", "lieux"),
    ("a market", "un marché", "lieux"),
    ("a shopping mall", "un centre commercial", "lieux"),
    ("a store / a shop", "un magasin", "lieux"),
    ("a department store", "un grand magasin", "lieux"),
    ("a supermarket", "un supermarché", "lieux"),
    ("a bakery", "une boulangerie", "lieux"),
    ("a suburb", "une banlieue", "lieux"),
    ("downtown / the city center", "le centre-ville", "lieux"),
    ("the countryside", "la campagne", "lieux"),
    ("a basement", "un sous-sol", "lieux"),
    ("a rooftop", "un toit-terrasse", "lieux"),
    ("a hallway / a corridor", "un couloir", "lieux"),
    ("a staircase", "un escalier", "lieux"),
    ("an entrance", "une entrée", "lieux"),
    ("an exit", "une sortie", "lieux"),

    # ── Complément métiers ──
    ("a lawyer / an attorney", "un avocat", "métiers"),
    ("an engineer", "un ingénieur", "métiers"),
    ("an architect", "un architecte", "métiers"),
    ("a doctor / a physician", "un médecin", "métiers"),
    ("a surgeon", "un chirurgien", "métiers"),
    ("a dentist", "un dentiste", "métiers"),
    ("a pharmacist", "un pharmacien", "métiers"),
    ("a teacher", "un enseignant", "métiers"),
    ("a professor", "un professeur (université)", "métiers"),
    ("a researcher", "un chercheur", "métiers"),
    ("a scientist", "un scientifique", "métiers"),
    ("a journalist / a reporter", "un journaliste", "métiers"),
    ("an editor", "un rédacteur en chef", "métiers"),
    ("a translator", "un traducteur", "métiers"),
    ("an electrician", "un électricien", "métiers"),
    ("a plumber", "un plombier", "métiers"),
    ("a mechanic", "un mécanicien", "métiers"),
    ("a carpenter", "un charpentier", "métiers"),
    ("a technician", "un technicien", "métiers"),
    ("a salesperson", "un vendeur", "métiers"),
    ("a cashier", "un caissier", "métiers"),
    ("a receptionist", "un réceptionniste", "métiers"),
    ("a secretary", "un secrétaire", "métiers"),
    ("an assistant", "un assistant", "métiers"),
    ("a supervisor", "un superviseur", "métiers"),
    ("an entrepreneur", "un entrepreneur", "métiers"),
    ("a consultant", "un consultant", "métiers"),
    ("an analyst", "un analyste", "métiers"),
    ("a chef / a cook", "un cuisinier", "métiers"),
    ("a farmer", "un agriculteur", "métiers"),
    ("a fisherman", "un pêcheur", "métiers"),

    # ── Complément communication ──
    ("a request", "une demande", "communication"),
    ("a confirmation", "une confirmation", "communication"),
    ("a response", "une réponse", "communication"),
    ("a greeting", "une salutation", "communication"),
    ("a remark", "une remarque", "communication"),
    ("a statement", "une déclaration", "communication"),
    ("a phone number", "un numéro de téléphone", "communication"),
    ("a contact", "un contact", "communication"),
    ("a conversation", "une conversation", "communication"),
    ("a discussion", "une discussion", "communication"),
    ("a negotiation", "une négociation", "communication"),
    ("an agreement", "un accord", "communication"),
    ("a disagreement", "un désaccord", "communication"),
    ("a presentation", "une présentation", "communication"),
    ("an audience", "un public / une audience", "communication"),
    ("an opinion / a viewpoint", "un avis / une opinion", "communication"),
    ("a suggestion", "une suggestion", "communication"),
    ("a clarification", "une clarification", "communication"),
    ("a postcard", "une carte postale", "communication"),
    ("a parcel / a package", "un colis", "communication"),
    ("a stamp", "un timbre", "communication"),
    ("a mailbox / a letterbox", "une boîte aux lettres", "communication"),
    ("a hotline", "une ligne d'assistance", "communication"),
    ("a headset", "un casque (téléphonique)", "communication"),

    # ── Complément transport ──
    ("a bicycle / a bike", "un vélo", "transport"),
    ("a motorcycle / a motorbike", "une moto", "transport"),
    ("a van", "une camionnette", "transport"),
    ("a taxi / a cab", "un taxi", "transport"),
    ("a coach", "un autocar", "transport"),
    ("a tram / a streetcar", "un tramway", "transport"),
    ("a helicopter", "un hélicoptère", "transport"),
    ("a boat", "un bateau", "transport"),
    ("a ship", "un navire", "transport"),
    ("a yacht", "un yacht", "transport"),
    ("an aircraft", "un aéronef", "transport"),
    ("a runway", "une piste (d'aéroport)", "transport"),
    ("a terminal", "un terminal", "transport"),
    ("a dock", "un quai (port)", "transport"),
    ("a bridge", "un pont", "transport"),
    ("a tunnel", "un tunnel", "transport"),
    ("a route", "un itinéraire", "transport"),
    ("a destination", "une destination", "transport"),
    ("a departure", "un départ", "transport"),
    ("an arrival", "une arrivée", "transport"),
    ("a journey / a trip", "un trajet", "transport"),
    ("the mileage", "le kilométrage", "transport"),

    # ── Complément marketing ──
    ("a logo", "un logo", "marketing"),
    ("a slogan", "un slogan", "marketing"),
    ("a campaign", "une campagne", "marketing"),
    ("a target audience", "un public cible", "marketing"),
    ("a market share", "une part de marché", "marketing"),
    ("a competitor", "un concurrent", "marketing"),
    ("competition", "la concurrence", "marketing"),
    ("a consumer", "un consommateur", "marketing"),
    ("a product launch", "un lancement de produit", "marketing"),
    ("a coupon / a voucher", "un bon de réduction", "marketing"),
    ("a billboard", "un panneau publicitaire", "marketing"),
    ("a commercial", "une publicité (télé)", "marketing"),
    ("a catalog / a catalogue", "un catalogue", "marketing"),
    ("market research", "une étude de marché", "marketing"),
    ("a focus group", "un groupe de discussion", "marketing"),
    ("word of mouth", "le bouche-à-oreille", "marketing"),
    ("a testimonial", "un témoignage client", "marketing"),
    ("brand awareness", "la notoriété de marque", "marketing"),
    ("a niche", "une niche", "marketing"),
    ("a trade fair / a trade show", "un salon professionnel", "marketing"),
    ("a booth / a stand", "un stand", "marketing"),

    # ── Complément industrie ──
    ("manufacturing", "la fabrication", "industrie"),
    ("an assembly line", "une chaîne de montage", "industrie"),
    ("a production line", "une ligne de production", "industrie"),
    ("raw materials", "les matières premières", "industrie"),
    ("machinery", "les machines", "industrie"),
    ("a conveyor belt", "un tapis roulant", "industrie"),
    ("a forklift", "un chariot élévateur", "industrie"),
    ("a supplier", "un fournisseur", "industrie"),
    ("a supply chain", "une chaîne d'approvisionnement", "industrie"),
    ("inventory / stock", "le stock", "industrie"),
    ("output", "la production / le rendement", "industrie"),
    ("productivity", "la productivité", "industrie"),
    ("quality control", "le contrôle qualité", "industrie"),
    ("a defect", "un défaut", "industrie"),
    ("a prototype", "un prototype", "industrie"),
    ("safety goggles", "des lunettes de protection", "industrie"),
    ("a hard hat", "un casque de chantier", "industrie"),
    ("maintenance", "la maintenance", "industrie"),

    # ── Complément informatique ──
    ("a keyboard", "un clavier", "informatique"),
    ("a screen / a monitor", "un écran", "informatique"),
    ("a scanner", "un scanner", "informatique"),
    ("a hard drive", "un disque dur", "informatique"),
    ("a server", "un serveur", "informatique"),
    ("a router", "un routeur", "informatique"),
    ("software", "un logiciel", "informatique"),
    ("hardware", "le matériel informatique", "informatique"),
    ("a download", "un téléchargement", "informatique"),

    # ── Complément environnement ──
    ("pollution", "la pollution", "environnement"),
    ("recycling", "le recyclage", "environnement"),
    ("renewable energy", "les énergies renouvelables", "environnement"),
    ("climate change", "le changement climatique", "environnement"),
    ("a carbon footprint", "une empreinte carbone", "environnement"),

    # ── Complément objets ──
    ("a stapler", "une agrafeuse", "objets"),
    ("a paperclip", "un trombone", "objets"),
    ("scissors", "des ciseaux", "objets"),
]


def seed():
    db = SessionLocal()
    existants = {m.anglais for m in db.query(Mot).all()}
    nouveaux = [Mot(anglais=a, francais=f, categorie=c) for a, f, c in VOCABULAIRE if a not in existants]
    if nouveaux:
        db.add_all(nouveaux)
        db.commit()
        print(f"{len(nouveaux)} mots ajoutés.")
    else:
        print("Base déjà à jour.")
    db.close()


if __name__ == "__main__":
    seed()
