from database import SessionLocal, engine, Base
from models import Mot

Base.metadata.create_all(bind=engine)

VOCABULAIRE = [
    # ── Emploi / RH ──────────────────────────────────────────
    ("a company", "une entreprise", "emploi"),
    ("a job", "un travail", "emploi"),
    ("a job interview", "un entretien d'embauche", "emploi"),
    ("to fire someone", "licencier quelqu'un", "emploi"),
    ("to hire someone", "embaucher quelqu'un", "emploi"),
    ("to get a job", "obtenir un poste", "emploi"),
    ("salary", "salaire", "emploi"),
    ("a raise", "une augmentation", "emploi"),
    ("a course / a training", "une formation", "emploi"),
    ("a promotion", "une promotion", "emploi"),
    ("employment", "l'emploi", "emploi"),
    ("a CV / a résumé", "un CV", "emploi"),
    ("a job application", "une candidature", "emploi"),
    ("the skills", "les compétences", "emploi"),
    ("a colleague / a coworker", "le collègue", "emploi"),
    ("a deadline", "la date limite", "emploi"),
    ("a position", "le poste", "emploi"),
    ("to terminate", "licencier", "emploi"),
    ("a corporation", "une société", "emploi"),
    ("the corporate world", "le monde du travail", "emploi"),
    ("the workplace", "le lieu de travail", "emploi"),
    ("workload", "la charge de travail", "emploi"),
    ("to work overtime", "faire des heures supplémentaires", "emploi"),
    ("layoff", "le licenciement", "emploi"),
    ("shift", "la période de travail", "emploi"),
    ("to work part-time", "travailler à temps partiel", "emploi"),
    ("to work full-time", "travailler à temps plein", "emploi"),
    ("perks", "avantages en nature", "emploi"),
    ("payroll", "la paie", "emploi"),
    ("the job market", "le marché de l'emploi", "emploi"),
    ("termination notice", "l'avis de licenciement", "emploi"),
    ("human resources", "les ressources humaines", "emploi"),
    ("career path", "la trajectoire de carrière", "emploi"),
    ("retirement", "la retraite", "emploi"),
    ("teamwork", "le travail d'équipe", "emploi"),
    ("job satisfaction", "la satisfaction au travail", "emploi"),
    ("skillset", "l'ensemble de compétences", "emploi"),
    ("performance review", "l'évaluation de performance", "emploi"),
    ("temporary work", "le travail temporaire", "emploi"),
    ("work-life balance", "l'équilibre travail-vie", "emploi"),
    ("amenities", "équipements", "emploi"),
    ("memo", "une note de service", "emploi"),
    ("meeting", "réunion", "emploi"),
    ("to gather / to meet", "se réunir", "emploi"),
    ("a schedule", "un emploi du temps", "emploi"),
    ("a manager", "un responsable", "emploi"),
    ("to apply for a job", "postuler pour un poste", "emploi"),
    ("a workshop", "un atelier", "emploi"),
    ("an invoice", "une facture", "emploi"),
    ("an applicant", "un candidat", "emploi"),
    ("catering", "restauration", "emploi"),
    ("to attend a conference", "participer à une conférence", "emploi"),
    ("a desk / an office", "un bureau", "emploi"),
    ("overtime", "heures supplémentaires", "emploi"),
    ("education", "les études", "emploi"),
    ("diploma", "diplôme", "emploi"),
    ("certificate", "certification", "emploi"),
    ("award", "récompense", "emploi"),
    ("contractor", "un sous-traitant", "emploi"),
    ("a freelancer", "un freelance", "emploi"),
    ("to commute", "faire le trajet domicile-travail", "emploi"),
    ("trainee / an intern", "stagiaire", "emploi"),
    ("internship", "stage", "emploi"),
    ("an executive", "un cadre", "emploi"),
    ("team", "équipe", "emploi"),
    ("the boss", "le patron / la patronne", "emploi"),
    ("to clock in", "pointer", "emploi"),
    ("benefits", "avantages", "emploi"),
    ("a company car", "une voiture de société", "emploi"),
    ("to retire", "prendre sa retraite", "emploi"),
    ("a sick leave", "congé maladie", "emploi"),
    ("headquarters", "quartier général / siège social", "emploi"),
    ("leisure", "loisirs", "emploi"),
    ("an income", "revenu", "emploi"),
    ("jobless", "sans emploi", "emploi"),
    ("a complaint", "une plainte", "emploi"),
    ("an employee", "un employé", "emploi"),
    ("an employer", "un employeur", "emploi"),
    ("to be self-employed", "travailler à son compte", "emploi"),
    ("a vacancy", "un poste vacant", "emploi"),

    # ── Divertissement / Vie sociale ─────────────────────────
    ("to eat out", "manger au restaurant", "divertissement"),
    ("take-away", "à emporter", "divertissement"),
    ("appetizers", "apéritif", "divertissement"),
    ("starters", "l'entrée", "divertissement"),
    ("a dish", "un plat", "divertissement"),
    ("enjoy your meal", "bon appétit", "divertissement"),
    ("the main course", "le plat principal", "divertissement"),
    ("leftovers", "des restes", "divertissement"),
    ("to order", "commander", "divertissement"),
    ("the bill", "l'addition", "divertissement"),
    ("a tip", "un pourboire", "divertissement"),
    ("a waiter / a waitress", "un serveur", "divertissement"),
    ("napkin", "serviette", "divertissement"),
    ("to binge watch", "regarder pleins de séries de suite", "divertissement"),
    ("TV series", "une série", "divertissement"),
    ("the movie theatre / the cinema", "cinéma", "divertissement"),
    ("a movie", "un film", "divertissement"),
    ("a documentary", "un documentaire", "divertissement"),
    ("to shoot", "filmer / tourner", "divertissement"),
    ("a biopic", "une biographie filmée", "divertissement"),
    ("sci-fi", "film de science-fiction", "divertissement"),
    ("entertaining", "divertissant", "divertissement"),
    ("to play an instrument", "jouer un instrument", "divertissement"),
    ("to hang out with", "traîner avec", "divertissement"),
    ("customer", "client", "divertissement"),
    ("reservation / booking", "réservation", "divertissement"),
    ("clerk", "vendeur", "divertissement"),
    ("a beverage", "une boisson", "divertissement"),
    ("groceries", "courses / provisions", "divertissement"),
    ("cart", "chariot", "divertissement"),
    ("a discount", "une promotion / remise", "divertissement"),
    ("abroad", "à l'étranger", "divertissement"),
    ("price tag", "étiquette de prix", "divertissement"),
    ("junk food", "malbouffe", "divertissement"),
    ("affordable", "abordable", "divertissement"),
    ("shelf", "étagère", "divertissement"),
    ("cheap", "bon marché", "divertissement"),
    ("expensive", "cher", "divertissement"),
    ("range", "gamme", "divertissement"),
    ("organic", "bio", "divertissement"),
    ("the checkout", "la caisse", "divertissement"),
    ("cartoon", "dessin animé", "divertissement"),
    ("to be released", "sortir (au cinéma)", "divertissement"),
    ("to edit", "monter (un film)", "divertissement"),
    ("soap opera", "une comédie à l'eau de rose", "divertissement"),
    ("romcom", "comédie romantique", "divertissement"),
    ("a scriptwriter", "un scénariste", "divertissement"),
    ("the plot", "l'intrigue", "divertissement"),
    ("a trailer", "la bande annonce", "divertissement"),
    ("to go to the cinema", "aller au cinéma", "divertissement"),
    ("to dub", "doubler", "divertissement"),
    ("subtitles", "sous-titres", "divertissement"),
    ("hairdresser", "coiffeur", "divertissement"),
    ("actor", "acteur", "divertissement"),
    ("a stunt", "une cascade / un cascadeur", "divertissement"),
    ("exhibition", "une exposition", "divertissement"),
    ("landscape", "paysage", "divertissement"),
    ("drawing", "dessin", "divertissement"),
    ("painting", "peinture / tableau", "divertissement"),
    ("painter", "peintre", "divertissement"),
    ("guided tour", "visite guidée", "divertissement"),
    ("jewellery", "bijoux", "divertissement"),
    ("sewing", "couture", "divertissement"),
    ("knitting", "tricot", "divertissement"),
    ("baking", "pâtisserie", "divertissement"),
    ("a gig", "un concert", "divertissement"),
    ("to go clubbing", "sortie en boîte", "divertissement"),
    ("a nightclub", "une boîte de nuit", "divertissement"),
    ("to be drunk", "être bourré", "divertissement"),
    ("darts", "les fléchettes", "divertissement"),
    ("to listen to music", "écouter de la musique", "divertissement"),
    ("an amusement park", "un parc d'attraction", "divertissement"),
    ("a rollercoaster", "les montagnes russes", "divertissement"),
    ("a fair", "une foire", "divertissement"),
    ("swimming", "natation", "divertissement"),
    ("a mall / a shopping center", "un centre commercial", "divertissement"),
    ("a suit", "un costume", "divertissement"),
    ("a sweater", "un pull", "divertissement"),
    ("soccer / football", "football", "divertissement"),
    ("clothes", "vêtements", "divertissement"),
    ("a cook", "un cuisinier", "divertissement"),
    ("to afford", "pouvoir s'offrir", "divertissement"),

    # ── Finance / Économie ───────────────────────────────────
    ("GDP", "PIB", "finance"),
    ("economy", "économie", "finance"),
    ("bankruptcy", "faillite", "finance"),
    ("cash", "espèces / liquidités", "finance"),
    ("consumption", "consommation", "finance"),
    ("cost", "coût", "finance"),
    ("currency", "monnaie / devise", "finance"),
    ("deficit", "déficit", "finance"),
    ("deposit", "acompte / dépôt", "finance"),
    ("growth", "croissance", "finance"),
    ("household", "un foyer", "finance"),
    ("interest rate", "taux d'intérêt", "finance"),
    ("purchasing power", "pouvoir d'achat", "finance"),
    ("scarcity", "rareté", "finance"),
    ("shortage", "pénurie", "finance"),
    ("gross", "brut", "finance"),
    ("a merger", "une fusion", "finance"),
    ("advertising", "publicité", "finance"),
    ("accounting", "comptabilité", "finance"),
    ("an accountant", "un comptable", "finance"),
    ("a bank", "une banque", "finance"),
    ("a banker", "un banquier", "finance"),
    ("a mortgage", "un prêt immobilier", "finance"),
    ("a loan", "un prêt", "finance"),
    ("to loan", "prêter", "finance"),
    ("to borrow", "emprunter", "finance"),
    ("a transfer", "un virement", "finance"),
    ("to withdraw money", "retirer de l'argent", "finance"),
    ("a bank account", "un compte bancaire", "finance"),
    ("a bank clerk", "un employé de banque", "finance"),
    ("a credit card", "une carte de crédit", "finance"),
    ("to pay cash", "payer en espèces", "finance"),
    ("savings", "l'épargne", "finance"),
    ("a savings account", "un compte épargne", "finance"),
    ("a checking account", "compte chèque", "finance"),
    ("to save money", "économiser de l'argent", "finance"),
    ("balance sheet", "bilan", "finance"),
    ("liabilities", "dettes / engagements", "finance"),
    ("an asset", "un actif / un atout", "finance"),
    ("to invest", "investir", "finance"),
    ("real estate", "l'immobilier", "finance"),
    ("shareholder", "actionnaire", "finance"),
    ("inheritance", "héritage", "finance"),
    ("compound interest", "intérêt composé", "finance"),
    ("fees", "frais", "finance"),
    ("tax", "taxe / impôt", "finance"),
    ("debt", "la dette", "finance"),
    ("cash flow", "flux de trésorerie", "finance"),
    ("equity", "capitaux propres", "finance"),
    ("ROI", "retour sur investissement", "finance"),
    ("crowdfunding", "financement participatif", "finance"),
    ("a broker", "un courtier", "finance"),
    ("turnover", "le chiffre d'affaires", "finance"),
    ("loss", "pertes", "finance"),
    ("to merge", "fusionner", "finance"),
    ("overdraft", "découvert", "finance"),
    ("the stock exchange", "la bourse", "finance"),
    ("shares", "actions", "finance"),
    ("profit", "le profit", "finance"),
    ("margin", "la marge", "finance"),
    ("hedge fund", "fonds spéculatif", "finance"),
    ("money laundering", "le blanchiment d'argent", "finance"),
    ("a coin", "une pièce", "finance"),
    ("a banknote", "un billet", "finance"),
    ("to grant a loan", "accorder un crédit", "finance"),

    # ── Informatique ─────────────────────────────────────────
    ("computer", "ordinateur", "informatique"),
    ("desktop", "ordinateur de bureau", "informatique"),
    ("laptop", "ordinateur portable", "informatique"),
    ("keyboard", "clavier", "informatique"),
    ("to sign up", "s'inscrire", "informatique"),
    ("a software", "un logiciel", "informatique"),
    ("database", "base de données", "informatique"),
    ("a network", "un réseau", "informatique"),
    ("user interface", "interface utilisateur", "informatique"),
    ("to log in", "se connecter", "informatique"),
    ("to log out", "se déconnecter", "informatique"),
    ("firewall", "pare-feu", "informatique"),
    ("to delete", "effacer / supprimer", "informatique"),
    ("to download", "télécharger", "informatique"),
    ("to update", "mettre à jour", "informatique"),
    ("a file", "un fichier", "informatique"),
    ("a printer", "une imprimante", "informatique"),
    ("a link", "un lien", "informatique"),
    ("to upload", "mettre en ligne", "informatique"),
    ("a user", "un utilisateur", "informatique"),
    ("online", "en ligne", "informatique"),
    ("to attach", "mettre en pièce jointe", "informatique"),
    ("a spreadsheet", "un tableur", "informatique"),
    ("an attachment", "une pièce jointe", "informatique"),
    ("a graph", "un graphique", "informatique"),
    ("to cancel", "annuler", "informatique"),
    ("to click", "cliquer", "informatique"),
    ("a homepage", "une page d'accueil", "informatique"),
    ("memory", "mémoire", "informatique"),
    ("a screen", "un écran", "informatique"),
    ("digital", "numérique", "informatique"),
    ("USB key", "une clé USB", "informatique"),
    ("a mouse", "une souris", "informatique"),
    ("a folder", "un dossier", "informatique"),
    ("to reboot", "redémarrer", "informatique"),
    ("a search engine", "un moteur de recherche", "informatique"),
    ("ink cartridge", "une cartouche d'encre", "informatique"),
    ("a backup", "une sauvegarde", "informatique"),
    ("a password", "mot de passe", "informatique"),
    ("a browser", "un navigateur", "informatique"),
    ("malware", "logiciel malveillant", "informatique"),
    ("troubleshooting", "dépannage", "informatique"),
    ("wireless", "sans fil", "informatique"),
    ("cloud storage", "stockage en ligne", "informatique"),
    ("server", "serveur", "informatique"),
    ("a tab", "un onglet", "informatique"),
    ("an email address", "une adresse mail", "informatique"),
    ("a newsletter", "une lettre d'information", "informatique"),
    ("to register", "s'inscrire", "informatique"),
    ("a username", "un identifiant de connexion", "informatique"),
    ("to forward", "transférer (un mail)", "informatique"),

    # ── Environnement / Météo / Santé ────────────────────────
    ("the weather", "la météo", "environnement"),
    ("the weather forecast", "les prévisions météo", "environnement"),
    ("sunny", "ensoleillé", "environnement"),
    ("cloudy", "nuageux", "environnement"),
    ("rainy", "pluvieux", "environnement"),
    ("snowy", "neigeux", "environnement"),
    ("windy", "venteux", "environnement"),
    ("icy", "glacé", "environnement"),
    ("foggy", "avec du brouillard", "environnement"),
    ("freezing", "gelé / très froid", "environnement"),
    ("warm", "chaud / doux", "environnement"),
    ("a storm", "une tempête", "environnement"),
    ("thunder", "l'orage", "environnement"),
    ("a cloud", "un nuage", "environnement"),
    ("a breeze", "une brise", "environnement"),
    ("unpredictable", "imprévisible", "environnement"),
    ("clear", "sans nuage", "environnement"),
    ("to warn", "prévenir", "environnement"),
    ("chilly", "frisquet / froid", "environnement"),
    ("flood", "inondation", "environnement"),
    ("drought", "sécheresse", "environnement"),
    ("heat wave", "vague de chaleur", "environnement"),
    ("frost", "gel", "environnement"),
    ("mild", "doux", "environnement"),
    ("lightning", "éclair", "environnement"),
    ("partly cloudy", "partiellement couvert", "environnement"),
    ("overcast", "couvert / nuageux", "environnement"),
    ("puddle", "flaque", "environnement"),
    ("rainbow", "arc-en-ciel", "environnement"),
    ("sunshine", "rayon de soleil", "environnement"),
    ("sunset", "coucher de soleil", "environnement"),
    ("sunrise", "lever de soleil", "environnement"),
    ("dawn", "aube", "environnement"),
    ("dusk", "crépuscule", "environnement"),
    ("snowflake", "flocon de neige", "environnement"),
    ("earthquake", "tremblement de terre", "environnement"),
    ("a headache", "un mal de tête", "environnement"),
    ("to work out", "s'entraîner", "environnement"),
    ("harmful", "nuisible", "environnement"),
    ("overweight", "en surpoids", "environnement"),
    ("healthy", "bon pour la santé", "environnement"),
    ("global warming", "réchauffement climatique", "environnement"),
    ("spring", "printemps", "environnement"),
    ("fall / autumn", "automne", "environnement"),
    ("winter", "hiver", "environnement"),
    ("summer", "été", "environnement"),
    ("eco-friendly", "respectueux de l'environnement", "environnement"),
    ("garbage", "déchets", "environnement"),
    ("sick", "malade", "environnement"),
    ("an injury", "une blessure", "environnement"),
    ("to be injured", "être blessé", "environnement"),
    ("disabled", "handicapé", "environnement"),
    ("wheelchair", "chaise roulante", "environnement"),
    ("to recycle", "recycler", "environnement"),
    ("to sort / to declutter", "trier", "environnement"),

    # ── Marketing / Vente ────────────────────────────────────
    ("subscription", "abonnement", "marketing"),
    ("a flyer", "un prospectus", "marketing"),
    ("to launch", "lancer", "marketing"),
    ("membership", "adhésion", "marketing"),
    ("survey", "une enquête", "marketing"),
    ("a form", "un formulaire", "marketing"),
    ("a venue", "un lieu / une salle", "marketing"),
    ("a brochure", "une brochure", "marketing"),
    ("announcement", "une annonce", "marketing"),
    ("an event", "un événement", "marketing"),
    ("available", "disponible", "marketing"),
    ("a brand", "une marque", "marketing"),
    ("a speech", "un discours", "marketing"),
    ("a bargain", "une bonne affaire", "marketing"),
    ("sustainable", "durable", "marketing"),
    ("guarantee", "une garantie", "marketing"),
    ("to retail", "vente au détail", "marketing"),
    ("wholesale", "en gros", "marketing"),
    ("to sell", "vendre", "marketing"),
    ("to buy / to purchase", "acheter", "marketing"),
    ("to pay back", "rembourser", "marketing"),
    ("a coupon", "un bon d'achat", "marketing"),
    ("sales", "les soldes", "marketing"),
    ("for sale", "en vente", "marketing"),
    ("to rent", "louer", "marketing"),
    ("upscale", "haut de gamme", "marketing"),
    ("a sample", "un échantillon", "marketing"),
    ("packaging", "emballage / conditionnement", "marketing"),
    ("storage", "stockage", "marketing"),
    ("shipping", "transport / expédition", "marketing"),
    ("delivery", "livraison", "marketing"),
    ("a shop / a store", "un magasin", "marketing"),
    ("money back guarantee", "satisfait ou remboursé", "marketing"),
    ("features", "caractéristiques", "marketing"),
    ("competitors", "les concurrents", "marketing"),
    ("the competition", "la concurrence", "marketing"),

    # ── Voyage ───────────────────────────────────────────────
    ("a journey", "un voyage / un trajet", "voyage"),
    ("location", "lieu", "voyage"),
    ("to go sightseeing", "faire du tourisme", "voyage"),
    ("a view", "une vue", "voyage"),
    ("to travel", "voyager", "voyage"),
    ("to stay", "rester / séjourner", "voyage"),
    ("to postpone", "reporter à plus tard", "voyage"),
    ("to book", "réserver", "voyage"),
    ("a booking", "une réservation", "voyage"),
    ("holiday / vacation", "vacances", "voyage"),
    ("a trip", "un séjour / un trajet", "voyage"),
    ("a campsite", "un camping", "voyage"),
    ("a motor home", "un camping-car", "voyage"),
    ("a flight", "un vol", "voyage"),
    ("a boarding pass", "une carte d'embarquement", "voyage"),
    ("to check in", "enregistrer ses bagages", "voyage"),
    ("luggage / baggage", "bagages", "voyage"),
    ("to pack / unpack your bag", "faire / défaire son sac", "voyage"),
    ("to take off", "décoller", "voyage"),
    ("to land", "atterrir", "voyage"),
    ("to pick up someone", "aller chercher quelqu'un", "voyage"),
    ("to drop off someone", "déposer quelqu'un", "voyage"),
    ("to be delayed", "être en retard", "voyage"),
    ("the gate", "la porte d'embarquement", "voyage"),
    ("an aisle seat", "un siège côté couloir", "voyage"),
    ("a carry-on", "un sac cabine", "voyage"),
    ("a connection", "une correspondance", "voyage"),
    ("a complimentary meal", "un repas offert", "voyage"),
    ("a bumpy flight", "un vol avec des turbulences", "voyage"),
    ("an ID card", "une carte d'identité", "voyage"),
    ("to be free of charge", "être gratuit", "voyage"),
    ("to fasten the seat belt", "attacher la ceinture", "voyage"),
    ("a return ticket", "un billet aller-retour", "voyage"),
    ("a one way ticket", "un billet aller simple", "voyage"),
    ("rush hour", "l'heure de pointe", "voyage"),
    ("package holiday", "vacances à forfait", "voyage"),
    ("a cruise", "une croisière", "voyage"),
    ("a cruise ship", "un bateau de croisière", "voyage"),
    ("an ATM / a cash machine", "un distributeur automatique de billets", "voyage"),
    ("to be fully booked", "être complet", "voyage"),
    ("a single room", "une chambre simple", "voyage"),
    ("to pay upfront", "payer à l'avance", "voyage"),
    ("a locker", "un casier", "voyage"),
    ("a safe", "un coffre-fort", "voyage"),
    ("air conditioning / AC", "la climatisation", "voyage"),
    ("a kettle", "une bouilloire", "voyage"),
    ("a dorm", "un dortoir", "voyage"),
    ("drivers licence", "permis de conduire", "voyage"),
    ("a backpack / a rucksack", "un sac à dos", "voyage"),
    ("a receipt", "un reçu / ticket de caisse", "voyage"),
    ("souvenirs", "des souvenirs", "voyage"),
    ("unforgettable", "inoubliable", "voyage"),
    ("crowded", "bondé", "voyage"),
    ("touristy", "touristique", "voyage"),
    ("to have a good time", "passer un bon moment", "voyage"),
    ("to rest", "se reposer", "voyage"),
    ("to be homesick", "avoir le mal du pays", "voyage"),
    ("a guided tour", "une visite guidée", "voyage"),
    ("a map", "une carte", "voyage"),
    ("the subway", "le métro", "voyage"),
    ("a cab / a taxi", "un taxi", "voyage"),
    ("the train station", "la gare", "voyage"),
    ("the platform", "le quai", "voyage"),
    ("to hike", "faire de la randonnée", "voyage"),
    ("passport", "passeport", "voyage"),
    ("visa", "visa", "voyage"),
    ("customs", "douane", "voyage"),
    ("car rental", "voiture de location", "voyage"),

    # ── Industrie / Transport / Logistique ───────────────────
    ("the supply chain", "la chaîne logistique", "industrie"),
    ("inventory", "l'inventaire", "industrie"),
    ("container", "conteneur", "industrie"),
    ("hub", "plateforme logistique", "industrie"),
    ("inventory shortage", "rupture de stock", "industrie"),
    ("lot number", "numéro de lot", "industrie"),
    ("order backlog", "carnet de commandes", "industrie"),
    ("racking", "rayonnage", "industrie"),
    ("shipping center", "centre d'expédition", "industrie"),
    ("stock management", "gestion des stocks", "industrie"),
    ("warehouse", "entrepôt", "industrie"),
    ("pallet rack", "palettier", "industrie"),
    ("to ship", "expédier", "industrie"),
    ("to deliver", "livrer", "industrie"),
    ("delay", "retard", "industrie"),
    ("a package", "un colis", "industrie"),
    ("to store", "entreposer", "industrie"),
    ("to handle", "manutentionner", "industrie"),
    ("to stack containers", "empiler les conteneurs", "industrie"),
    ("to receive", "réceptionner", "industrie"),
    ("to load", "charger", "industrie"),
    ("to unload", "décharger", "industrie"),
    ("aisle", "allée de circulation", "industrie"),
    ("technical specifications", "cahier des charges", "industrie"),
    ("goods", "marchandise", "industrie"),
    ("item", "article", "industrie"),
    ("delivery order / note", "bon de livraison", "industrie"),
    ("shipper", "chargeur / expéditeur", "industrie"),
    ("bar code", "code-barres", "industrie"),
    ("trailer", "remorque", "industrie"),
    ("logistics", "logistique", "industrie"),
    ("supplier / provider", "fournisseur", "industrie"),
    ("delivery date", "date de livraison", "industrie"),
    ("duties", "droit de douane", "industrie"),
    ("freight", "fret", "industrie"),
    ("out of stock", "en rupture de stock", "industrie"),
    ("upstream", "en amont", "industrie"),
    ("downstream", "en aval", "industrie"),
    ("requirements", "besoins", "industrie"),
    ("a truck / a lorry", "un camion", "industrie"),

    # ── Nouveau vocabulaire enrichi ──────────────────────────
    ("an advertisement", "une publicité", "marketing"),
    ("to advertise / to promote", "faire de la publicité / promouvoir", "verbes"),
    ("an agenda", "un ordre du jour / un programme", "communication"),
    ("to agree with", "être d'accord avec", "verbes"),
    ("to agree on", "s'accorder sur", "verbes"),
    ("a bid", "une enchère / une offre", "finance"),
    ("a bill", "une facture / une addition / un billet", "finance"),
    ("the blueprints", "un projet / un plan", "industrie"),
    ("to check", "vérifier", "verbes"),
    ("commuting", "le trajet domicile-travail", "emploi"),
    ("current", "actuel(le)", "général"),
    ("the damage", "les dégâts", "général"),
    ("the facilities", "les installations / les équipements", "emploi"),
    ("the furniture", "le mobilier", "objets"),
    ("the guidelines", "les directives / les recommandations", "emploi"),
    ("the hazard", "le danger / le risque", "général"),
    ("law", "la loi", "général"),
    ("a lawyer", "un avocat", "métiers"),
    ("to lay off / to dismiss", "licencier", "verbes"),
    ("a leak", "une fuite (de liquide)", "objets"),
    ("an owner / a proprietor", "un propriétaire", "emploi"),
    ("the premises", "les locaux d'une entreprise", "emploi"),
    ("to process", "traiter", "verbes"),
    ("to provide", "fournir", "verbes"),
    ("the purpose / the goal / the aim", "le but", "général"),
    ("a quote / a quotation", "un devis", "emploi"),
    ("a rate", "un tarif / un taux", "finance"),
    ("to require", "exiger", "verbes"),
    ("a retail store", "un magasin de vente au détail", "marketing"),
    ("a shipment", "une expédition / une cargaison", "industrie"),
    ("a submission", "une proposition soumise à une autorité", "emploi"),
    ("to subscribe", "s'abonner", "marketing"),
    ("the staff / the personnel", "le personnel", "emploi"),
    ("to fund / to finance", "financer", "verbes"),
    ("an application", "une candidature", "emploi"),
    ("the assets", "les liquidités / les avoirs", "finance"),
    ("the Board of Directors", "le conseil d'administration", "emploi"),

    # ── Objets du quotidien ──────────────────────────────────
    ("appliance", "appareil électroménager", "objets"),
    ("apron", "tablier", "objets"),
    ("baby carriage / pram", "landau", "objets"),
    ("bag", "sac", "objets"),
    ("bench", "banc", "objets"),
    ("board", "tableau (blanc / d'affichage)", "objets"),
    ("bookcase", "bibliothèque (meuble)", "objets"),
    ("booklet", "fascicule", "objets"),
    ("briefcase", "mallette", "objets"),
    ("cabinet", "meuble de rangement", "objets"),
    ("carpet / rug", "tapis", "objets"),
    ("chair", "chaise", "objets"),
    ("chart", "graphique", "objets"),
    ("clippers", "tondeuse à cheveux", "objets"),
    ("coal", "charbon", "objets"),
    ("conveyor belt", "tapis roulant", "objets"),
    ("counter", "comptoir", "objets"),
    ("crane", "grue", "objets"),
    ("cupboard", "placard", "objets"),
    ("drill", "perceuse", "objets"),
    ("elevator / lift", "ascenseur", "objets"),
    ("equipment", "équipement", "objets"),
    ("filing cabinet", "meuble de classement", "objets"),
    ("forklift", "chariot élévateur", "objets"),
    ("gloves", "gants", "objets"),
    ("guardrail", "glissière de sécurité", "objets"),
    ("heating", "chauffage", "objets"),
    ("helmet / hard hat", "casque", "objets"),
    ("hose", "tuyau d'arrosage", "objets"),
    ("ladder", "échelle", "objets"),
    ("lawnmower", "tondeuse à gazon", "objets"),
    ("menu", "carte au restaurant", "objets"),
    ("package / parcel", "paquet / colis", "objets"),
    ("phone directory", "annuaire téléphonique", "objets"),
    ("rope", "corde", "objets"),
    ("scale / scales", "balance", "objets"),
    ("shopping cart / trolley", "caddie", "objets"),
    ("sign", "panneau de signalisation", "objets"),
    ("sink", "évier", "objets"),
    ("sled / sledge", "luge", "objets"),
    ("slot", "case / fente / créneau", "objets"),
    ("spare part", "pièce de rechange", "objets"),
    ("stain", "tache", "objets"),
    ("stapler", "agrafeuse", "objets"),
    ("steel barrel", "baril en acier", "objets"),
    ("stretcher", "civière / brancard", "objets"),
    ("stroller / pushchair", "poussette", "objets"),
    ("tablecloth", "nappe", "objets"),
    ("tire / tyre", "pneu", "objets"),
    ("tool", "outil", "objets"),
    ("trolley", "chariot", "objets"),
    ("vacuum cleaner", "aspirateur", "objets"),
    ("vending machine", "distributeur automatique de nourriture", "objets"),
    ("wallet", "portefeuille", "objets"),
    ("wheelbarrow", "brouette", "objets"),

    # ── Métiers / Professions ────────────────────────────────
    ("architect", "architecte", "métiers"),
    ("baker", "boulanger", "métiers"),
    ("bellman", "groom", "métiers"),
    ("carmaker", "fabricant de voitures", "métiers"),
    ("carrier", "transporteur", "métiers"),
    ("cashier", "caissier", "métiers"),
    ("caterer", "traiteur", "métiers"),
    ("ceo", "PDG", "métiers"),
    ("chef", "chef cuisinier", "métiers"),
    ("cleaners", "teinturier", "métiers"),
    ("concierge", "réceptionniste", "métiers"),
    ("dealer", "revendeur / commerçant", "métiers"),
    ("doorman", "portier", "métiers"),
    ("driver", "chauffeur / conducteur", "métiers"),
    ("firefighter / fireman", "pompier", "métiers"),
    ("flight attendant", "hôtesse de l'air / steward", "métiers"),
    ("handler", "manutentionnaire", "métiers"),
    ("hotel clerk", "employé d'hôtel", "métiers"),
    ("jeweller / jeweler", "bijoutier", "métiers"),
    ("lecturer", "maître de conférence", "métiers"),
    ("mailman", "postier", "métiers"),
    ("mechanic", "mécanicien", "métiers"),
    ("pilot", "pilote", "métiers"),
    ("plumber", "plombier", "métiers"),
    ("real estate agent", "agent immobilier", "métiers"),
    ("repairman", "réparateur", "métiers"),
    ("secretary", "secrétaire", "métiers"),
    ("teller", "guichetier", "métiers"),

    # ── Lieux ────────────────────────────────────────────────
    ("bookshop", "librairie", "lieux"),
    ("bridge / overpass", "pont", "lieux"),
    ("cafeteria", "cafétéria / cantine", "lieux"),
    ("cellar", "cave", "lieux"),
    ("conference hall", "salle de conférence", "lieux"),
    ("construction site / work site", "chantier", "lieux"),
    ("department store / supermarket", "supermarché / grand magasin", "lieux"),
    ("diner", "restaurant américain", "lieux"),
    ("factory / plant", "usine", "lieux"),
    ("garden", "jardin", "lieux"),
    ("gas station / petrol station", "station-essence", "lieux"),
    ("laboratory", "laboratoire", "lieux"),
    ("lane", "voie", "lieux"),
    ("lawn", "pelouse", "lieux"),
    ("library", "bibliothèque", "lieux"),
    ("lobby", "hall d'hôtel", "lieux"),
    ("newsstand", "kiosque à journaux", "lieux"),
    ("sidewalk", "trottoir", "lieux"),
    ("toll booth", "péage", "lieux"),
    ("walkway", "passage piéton", "lieux"),

    # ── Vêtements / Accessoires ──────────────────────────────
    ("backpack", "sac à dos", "vêtements"),
    ("cap", "casquette", "vêtements"),
    ("garment", "vêtement", "vêtements"),
    ("glasses", "lunettes", "vêtements"),
    ("hat", "chapeau", "vêtements"),
    ("jacket", "veste", "vêtements"),
    ("long-sleeved", "à manches longues", "vêtements"),
    ("outfit", "tenue", "vêtements"),
    ("overalls", "combinaison de travail", "vêtements"),
    ("purse", "sac à main", "vêtements"),
    ("shirt", "chemise", "vêtements"),
    ("short-sleeved", "à manches courtes", "vêtements"),
    ("suitcase", "valise", "vêtements"),
    ("sunglasses", "lunettes de soleil", "vêtements"),
    ("tie", "cravate", "vêtements"),
    ("white coat / lab coat", "blouse blanche", "vêtements"),

    # ── Transport / Circulation ──────────────────────────────
    ("highway", "autoroute", "transport"),
    ("shuttle", "navette", "transport"),
    ("traffic lights", "feu de signalisation", "transport"),

    # ── Verbes ───────────────────────────────────────────────
    ("to accommodate", "loger", "verbes"),
    ("to attend", "assister à", "verbes"),
    ("to board", "monter à bord", "verbes"),
    ("to brake", "freiner", "verbes"),
    ("to buy / to purchase", "acheter", "verbes"),
    ("to call at", "faire escale à", "verbes"),
    ("to carry", "porter (un poids)", "verbes"),
    ("to cast a shadow", "jeter une ombre", "verbes"),
    ("to check-in", "enregistrer ses bagages", "verbes"),
    ("to chop", "hacher", "verbes"),
    ("to clear", "ranger", "verbes"),
    ("to climb", "grimper", "verbes"),
    ("to convey", "transporter", "verbes"),
    ("to cook", "cuisiner", "verbes"),
    ("to cross", "traverser", "verbes"),
    ("to dig", "creuser", "verbes"),
    ("to display / to exhibit", "exposer", "verbes"),
    ("to draw", "tirer / dessiner", "verbes"),
    ("to empty", "vider", "verbes"),
    ("to fall", "tomber", "verbes"),
    ("to feed", "nourrir", "verbes"),
    ("to fill (in)", "remplir", "verbes"),
    ("to fix / to mend / to repair", "réparer", "verbes"),
    ("to focus", "se concentrer", "verbes"),
    ("to fold", "plier", "verbes"),
    ("to gaze", "regarder avec insistance", "verbes"),
    ("to get off", "sortir de / descendre de", "verbes"),
    ("to gush", "jaillir", "verbes"),
    ("to hand somebody something", "tendre quelque chose à quelqu'un", "verbes"),
    ("to hang up", "raccrocher (le téléphone)", "verbes"),
    ("to hang", "pendre / suspendre / accrocher", "verbes"),
    ("to hit", "frapper / heurter", "verbes"),
    ("to hold", "tenir", "verbes"),
    ("to leak", "fuir (liquide)", "verbes"),
    ("to make a call", "passer un appel téléphonique", "verbes"),
    ("to make a copy", "faire une photocopie", "verbes"),
    ("to overlook", "négliger / ignorer", "verbes"),
    ("to overtake", "doubler (sur la route)", "verbes"),
    ("to pick somebody up", "passer prendre quelqu'un", "verbes"),
    ("to pick something up", "ramasser quelque chose", "verbes"),
    ("to pick up the phone", "décrocher (le téléphone)", "verbes"),
    ("to point to / at something", "pointer quelque chose du doigt", "verbes"),
    ("to pour", "verser", "verbes"),
    ("to raise one's hand", "lever la main", "verbes"),
    ("to sail", "naviguer", "verbes"),
    ("to service", "faire la maintenance", "verbes"),
    ("to set the table", "mettre la table", "verbes"),
    ("to shake hands", "se serrer la main", "verbes"),
    ("to sign", "signer", "verbes"),
    ("to sink", "couler / sombrer", "verbes"),
    ("to sit down", "s'asseoir", "verbes"),
    ("to sit", "être assis", "verbes"),
    ("to skid", "déraper", "verbes"),
    ("to slide", "glisser", "verbes"),
    ("to sort", "trier", "verbes"),
    ("to stack", "empiler", "verbes"),
    ("to stand up", "se lever", "verbes"),
    ("to stand", "être debout", "verbes"),
    ("to sweep", "balayer", "verbes"),
    ("to tower over / to overlook", "surplomber / dominer", "verbes"),
    ("to try on", "essayer (un vêtement)", "verbes"),
    ("to type", "taper à l'ordinateur", "verbes"),
    ("to wave", "faire signe de la main", "verbes"),
    ("to wear", "porter (un vêtement / accessoire)", "verbes"),
    ("to withdraw", "retirer", "verbes"),
    ("to write", "écrire", "verbes"),
]


def seed():
    db = SessionLocal()
    existants = {m.anglais for m in db.query(Mot).all()}
    nouveaux = [Mot(anglais=a, francais=f, categorie=c) for a, f, c in VOCABULAIRE if a not in existants]
    if nouveaux:
        db.add_all(nouveaux)
        db.commit()
        print(f"{len(nouveaux)} mots ajoutés.")
    else:
        print("Base déjà à jour.")
    db.close()


if __name__ == "__main__":
    seed()
